[2024-06-22 15:00:31,335: INFO: main: Starting Custom logging...]
[2024-06-22 15:43:38,234: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 15:43:38,237: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 15:51:03,414: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 15:51:03,418: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 15:51:03,423: INFO: common: created directory at: artifacts]
[2024-06-22 15:51:03,433: INFO: common: created directory at: artifacts/data_ingestion]
[2024-06-22 15:51:07,250: INFO: 2391244112:  file from url https://drive.google.com/uc?/export=download&id=1RmDs2j3QcY05ixoV1-ACmxmnM5xdmiGF downloaded and saved at path artifacts/data_ingestion/card_transdata.zip]
[2024-06-22 15:51:43,659: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 15:51:43,664: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 15:51:43,668: INFO: common: created directory at: artifacts]
[2024-06-22 15:51:43,671: INFO: common: created directory at: artifacts/data_ingestion]
[2024-06-22 15:51:43,676: INFO: 2391244112: File already exists of size: ~ 74490 KB]
[2024-06-22 15:51:50,647: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 15:51:50,652: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 15:51:50,655: INFO: common: created directory at: artifacts]
[2024-06-22 15:51:50,659: INFO: common: created directory at: artifacts/data_ingestion]
[2024-06-22 15:51:50,663: INFO: 2391244112: File already exists of size: ~ 74490 KB]
[2024-06-22 15:52:10,582: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 15:52:10,587: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 15:52:10,596: INFO: common: created directory at: artifacts]
[2024-06-22 15:52:10,609: INFO: common: created directory at: artifacts/data_ingestion]
[2024-06-22 15:52:14,945: INFO: 2391244112:  file from url https://drive.google.com/uc?/export=download&id=1RmDs2j3QcY05ixoV1-ACmxmnM5xdmiGF downloaded and saved at path artifacts/data_ingestion/card_transdata.zip]
[2024-06-22 15:54:15,295: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 15:54:15,302: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 15:54:15,318: INFO: common: created directory at: artifacts]
[2024-06-22 15:54:15,325: INFO: common: created directory at: artifacts/data_ingestion]
[2024-06-22 15:54:15,336: INFO: 2494678114: File already exists of size: ~ 74490 KB]
[2024-06-22 15:54:25,557: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 15:54:25,564: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 15:54:25,580: INFO: common: created directory at: artifacts]
[2024-06-22 15:54:25,606: INFO: common: created directory at: artifacts/data_ingestion]
[2024-06-22 15:54:30,180: INFO: 2494678114:  file from url https://drive.google.com/uc?/export=download&id=1RmDs2j3QcY05ixoV1-ACmxmnM5xdmiGF downloaded and saved at path artifacts/data_ingestion/card_transdata.zip]
[2024-06-22 15:54:47,959: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 15:54:47,963: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 15:54:47,966: INFO: common: created directory at: artifacts]
[2024-06-22 15:54:47,971: INFO: common: created directory at: artifacts/data_ingestion]
[2024-06-22 15:54:47,974: INFO: 2494678114: File already exists of size: ~ 74490 KB]
[2024-06-22 15:55:32,663: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 15:55:32,669: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 15:55:32,681: INFO: common: created directory at: artifacts]
[2024-06-22 15:55:32,689: INFO: common: created directory at: artifacts/data_ingestion]
[2024-06-22 15:55:32,694: INFO: 2494678114: File already exists of size: ~ 4 KB]
[2024-06-22 15:56:25,554: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 15:56:25,558: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 15:56:25,561: INFO: common: created directory at: artifacts]
[2024-06-22 15:56:25,563: INFO: common: created directory at: artifacts/data_ingestion]
[2024-06-22 15:56:28,634: INFO: 2494678114:  file from url https://drive.google.com/uc?/export=download&id=1RmDs2j3QcY05ixoV1-ACmxmnM5xdmiGF downloaded and saved at path artifacts/data_ingestion/card_transdata.csv]
[2024-06-22 16:13:57,884: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-06-22 16:13:57,886: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 16:13:57,888: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 16:13:57,889: INFO: common: created directory at: artifacts]
[2024-06-22 16:13:57,890: INFO: common: created directory at: artifacts/data_ingestion]
[2024-06-22 16:13:57,892: ERROR: stage_01_data_ingestion: name 'url' is not defined]
Traceback (most recent call last):
  File "/home/nair.ro/mlops-model-dev/src/XGBClassifier/pipeline/stage_01_data_ingestion.py", line 25, in <module>
    obj.main()
  File "/home/nair.ro/mlops-model-dev/src/XGBClassifier/pipeline/stage_01_data_ingestion.py", line 16, in main
    data_ingestion.download_file()
  File "/home/nair.ro/mlops-model-dev/src/XGBClassifier/components/data_ingestion.py", line 19, in download_file
    file_id = url.split("/")[-2]
NameError: name 'url' is not defined
[2024-06-22 16:15:35,743: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-06-22 16:15:35,745: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 16:15:35,747: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 16:15:35,748: INFO: common: created directory at: artifacts]
[2024-06-22 16:15:35,749: INFO: common: created directory at: artifacts/data_ingestion]
[2024-06-22 16:15:35,750: ERROR: stage_01_data_ingestion: name 'gdown' is not defined]
Traceback (most recent call last):
  File "/home/nair.ro/mlops-model-dev/src/XGBClassifier/pipeline/stage_01_data_ingestion.py", line 25, in <module>
    obj.main()
  File "/home/nair.ro/mlops-model-dev/src/XGBClassifier/pipeline/stage_01_data_ingestion.py", line 16, in main
    data_ingestion.download_file()
  File "/home/nair.ro/mlops-model-dev/src/XGBClassifier/components/data_ingestion.py", line 21, in download_file
    gdown.download(prefix+file_id, self.config.local_data_file)
NameError: name 'gdown' is not defined
[2024-06-22 16:15:47,108: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-06-22 16:15:47,111: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 16:15:47,113: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 16:15:47,114: INFO: common: created directory at: artifacts]
[2024-06-22 16:15:47,115: INFO: common: created directory at: artifacts/data_ingestion]
[2024-06-22 16:15:47,117: ERROR: stage_01_data_ingestion: name 'gdown' is not defined]
Traceback (most recent call last):
  File "/home/nair.ro/mlops-model-dev/src/XGBClassifier/pipeline/stage_01_data_ingestion.py", line 25, in <module>
    obj.main()
  File "/home/nair.ro/mlops-model-dev/src/XGBClassifier/pipeline/stage_01_data_ingestion.py", line 16, in main
    data_ingestion.download_file()
  File "/home/nair.ro/mlops-model-dev/src/XGBClassifier/components/data_ingestion.py", line 21, in download_file
    gdown.download(prefix+file_id, self.config.local_data_file)
NameError: name 'gdown' is not defined
[2024-06-22 16:16:00,694: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-06-22 16:16:00,697: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 16:16:00,698: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 16:16:00,699: INFO: common: created directory at: artifacts]
[2024-06-22 16:16:00,700: INFO: common: created directory at: artifacts/data_ingestion]
[2024-06-22 16:16:04,819: INFO: data_ingestion:  file from url https://drive.google.com/uc?/export=download&id=1RmDs2j3QcY05ixoV1-ACmxmnM5xdmiGF downloaded and saved at path artifacts/data_ingestion/card_transdata.csv]
[2024-06-22 16:16:04,834: INFO: data_ingestion:  File 'artifacts/data_ingestion/card_transdata.csv' is of type '.csv']
[2024-06-22 16:16:04,835: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-06-22 16:19:45,704: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-06-22 16:19:45,707: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 16:19:45,711: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 16:19:45,713: INFO: common: created directory at: artifacts]
[2024-06-22 16:19:45,714: INFO: common: created directory at: artifacts/data_ingestion]
[2024-06-22 16:19:50,031: INFO: data_ingestion:  file from url https://drive.google.com/uc?/export=download&id=1RmDs2j3QcY05ixoV1-ACmxmnM5xdmiGF downloaded and saved at path artifacts/data_ingestion/card_transdata.csv]
[2024-06-22 16:19:50,047: INFO: data_ingestion:  File 'artifacts/data_ingestion/card_transdata.csv' is of type '.csv']
[2024-06-22 16:19:50,048: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-06-22 16:22:39,245: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-06-22 16:22:39,249: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 16:22:39,252: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 16:22:39,255: INFO: common: created directory at: artifacts]
[2024-06-22 16:22:39,256: INFO: common: created directory at: artifacts/data_ingestion]
[2024-06-22 16:22:42,463: INFO: data_ingestion:  file from url https://drive.google.com/uc?/export=download&id=1RmDs2j3QcY05ixoV1-ACmxmnM5xdmiGF downloaded and saved at path artifacts/data_ingestion/card_transdata.csv]
[2024-06-22 16:22:42,485: INFO: data_ingestion:  File 'artifacts/data_ingestion/card_transdata.csv' is of type '.csv']
[2024-06-22 16:22:42,486: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-06-22 17:05:08,713: INFO: stage_02_prepare_base_model: *******************]
[2024-06-22 17:05:08,713: INFO: stage_02_prepare_base_model: >>>>>> stage Prepare base model started <<<<<<]
[2024-06-22 17:05:08,717: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 17:05:08,720: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 17:05:08,721: INFO: common: created directory at: artifacts]
[2024-06-22 17:05:08,725: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-06-22 17:05:08,725: ERROR: stage_02_prepare_base_model: "'ConfigBox' object has no attribute 'base_model_path'"]
Traceback (most recent call last):
  File "box/box.py", line 503, in box.box.Box.__getitem__
KeyError: 'base_model_path'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "box/box.py", line 536, in box.box.Box.__getattr__
  File "box/box.py", line 524, in box.box.Box.__getitem__
box.exceptions.BoxKeyError: "'base_model_path'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "box/box.py", line 538, in box.box.Box.__getattr__
AttributeError: 'ConfigBox' object has no attribute 'base_model_path'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "box/config_box.py", line 28, in box.config_box.ConfigBox.__getattr__
  File "box/box.py", line 552, in box.box.Box.__getattr__
box.exceptions.BoxKeyError: "'ConfigBox' object has no attribute 'base_model_path'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "box/box.py", line 503, in box.box.Box.__getitem__
KeyError: 'base_model_path'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "box/box.py", line 536, in box.box.Box.__getattr__
  File "box/box.py", line 524, in box.box.Box.__getitem__
box.exceptions.BoxKeyError: "'base_model_path'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "box/box.py", line 538, in box.box.Box.__getattr__
AttributeError: 'ConfigBox' object has no attribute 'base_model_path'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/nair.ro/mlops-model-dev/src/XGBClassifier/pipeline/stage_02_prepare_base_model.py", line 25, in <module>
    obj.main()
  File "/home/nair.ro/mlops-model-dev/src/XGBClassifier/pipeline/stage_02_prepare_base_model.py", line 14, in main
    prepare_base_model_config = config.get_prepare_base_model_config()
  File "/home/nair.ro/ChickenDiseasaeClassification/src/cnnClassifier/config/configuration.py", line 50, in get_prepare_base_model_config
    base_model_path=Path(config.base_model_path),
  File "box/config_box.py", line 30, in box.config_box.ConfigBox.__getattr__
  File "box/box.py", line 552, in box.box.Box.__getattr__
box.exceptions.BoxKeyError: "'ConfigBox' object has no attribute 'base_model_path'"
[2024-06-22 17:09:55,499: INFO: stage_02_prepare_base_model: *******************]
[2024-06-22 17:09:55,499: INFO: stage_02_prepare_base_model: >>>>>> stage Prepare base model started <<<<<<]
[2024-06-22 17:09:55,502: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 17:09:55,506: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 17:09:55,507: INFO: common: created directory at: artifacts]
[2024-06-22 17:09:55,508: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-06-22 17:09:55,508: ERROR: stage_02_prepare_base_model: name 'XGBClassifier' is not defined]
Traceback (most recent call last):
  File "/home/nair.ro/mlops-model-dev/src/XGBClassifier/pipeline/stage_02_prepare_base_model.py", line 26, in <module>
    obj.main()
  File "/home/nair.ro/mlops-model-dev/src/XGBClassifier/pipeline/stage_02_prepare_base_model.py", line 17, in main
    xgb = prepare_base_model.prepare_XGBClassifier_model()
  File "/home/nair.ro/mlops-model-dev/src/XGBClassifier/components/prepare_base_model.py", line 12, in prepare_XGBClassifier_model
    xgb = XGBClassifier(n_estimators=self.config.params_n_estimators ,
NameError: name 'XGBClassifier' is not defined
[2024-06-22 17:10:44,752: INFO: stage_02_prepare_base_model: *******************]
[2024-06-22 17:10:44,753: INFO: stage_02_prepare_base_model: >>>>>> stage Prepare base model started <<<<<<]
[2024-06-22 17:10:44,755: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 17:10:44,757: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 17:10:44,758: INFO: common: created directory at: artifacts]
[2024-06-22 17:10:44,759: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-06-22 17:10:44,760: ERROR: stage_02_prepare_base_model: name 'logger' is not defined]
Traceback (most recent call last):
  File "/home/nair.ro/mlops-model-dev/src/XGBClassifier/pipeline/stage_02_prepare_base_model.py", line 26, in <module>
    obj.main()
  File "/home/nair.ro/mlops-model-dev/src/XGBClassifier/pipeline/stage_02_prepare_base_model.py", line 17, in main
    xgb = prepare_base_model.prepare_XGBClassifier_model()
  File "/home/nair.ro/mlops-model-dev/src/XGBClassifier/components/prepare_base_model.py", line 16, in prepare_XGBClassifier_model
    logger.info(f"Initialized XGBClassifier with following parameters {self.config}")
NameError: name 'logger' is not defined
[2024-06-22 17:11:02,418: INFO: stage_02_prepare_base_model: *******************]
[2024-06-22 17:11:02,419: INFO: stage_02_prepare_base_model: >>>>>> stage Prepare base model started <<<<<<]
[2024-06-22 17:11:02,421: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 17:11:02,423: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 17:11:02,424: INFO: common: created directory at: artifacts]
[2024-06-22 17:11:02,425: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-06-22 17:11:02,426: INFO: prepare_base_model: Initialized XGBClassifier with following parameters PrepareBaseModelConfig(params_n_estimators=500, params_learning_rate=0.1, params_random_state=42, params_subsample=0.5, params_n_jobs=-1, params_max_depth=3)]
[2024-06-22 17:11:02,426: INFO: stage_02_prepare_base_model: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-06-22 17:12:39,495: INFO: stage_02_prepare_base_model: *******************]
[2024-06-22 17:12:39,495: INFO: stage_02_prepare_base_model: >>>>>> stage Prepare base model started <<<<<<]
[2024-06-22 17:12:39,498: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 17:12:39,500: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 17:12:39,500: INFO: common: created directory at: artifacts]
[2024-06-22 17:12:39,501: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-06-22 17:12:39,502: INFO: prepare_base_model: Initialized XGBClassifier with following parameters PrepareBaseModelConfig(params_n_estimators=500, params_learning_rate=0.1, params_random_state=42, params_subsample=0.5, params_n_jobs=-1, params_max_depth=3)]
[2024-06-22 17:12:39,503: INFO: stage_02_prepare_base_model: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-06-22 18:10:04,182: INFO: stage_03_training_cross_val: *******************]
[2024-06-22 18:10:04,182: INFO: stage_03_training_cross_val: >>>>>> stage Training started <<<<<<]
[2024-06-22 18:10:04,184: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 18:10:04,186: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 18:10:04,187: INFO: common: created directory at: artifacts]
[2024-06-22 18:10:04,188: ERROR: stage_03_training_cross_val: "'ConfigBox' object has no attribute 'local_data_file'"]
Traceback (most recent call last):
  File "box/box.py", line 503, in box.box.Box.__getitem__
KeyError: 'local_data_file'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "box/box.py", line 536, in box.box.Box.__getattr__
  File "box/box.py", line 524, in box.box.Box.__getitem__
box.exceptions.BoxKeyError: "'local_data_file'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "box/box.py", line 538, in box.box.Box.__getattr__
AttributeError: 'ConfigBox' object has no attribute 'local_data_file'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "box/config_box.py", line 28, in box.config_box.ConfigBox.__getattr__
  File "box/box.py", line 552, in box.box.Box.__getattr__
box.exceptions.BoxKeyError: "'ConfigBox' object has no attribute 'local_data_file'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "box/box.py", line 503, in box.box.Box.__getitem__
KeyError: 'local_data_file'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "box/box.py", line 536, in box.box.Box.__getattr__
  File "box/box.py", line 524, in box.box.Box.__getitem__
box.exceptions.BoxKeyError: "'local_data_file'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "box/box.py", line 538, in box.box.Box.__getattr__
AttributeError: 'ConfigBox' object has no attribute 'local_data_file'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/nair.ro/mlops-model-dev/src/XGBClassifier/pipeline/stage_03_training_cross_val.py", line 30, in <module>
    obj.main()
  File "/home/nair.ro/mlops-model-dev/src/XGBClassifier/pipeline/stage_03_training_cross_val.py", line 16, in main
    training_config = config.get_training_config()
  File "/home/nair.ro/mlops-model-dev/src/XGBClassifier/config_mngr/configuration_manager.py", line 60, in get_training_config
    training_data = self.config.local_data_file
  File "box/config_box.py", line 30, in box.config_box.ConfigBox.__getattr__
  File "box/box.py", line 552, in box.box.Box.__getattr__
box.exceptions.BoxKeyError: "'ConfigBox' object has no attribute 'local_data_file'"
[2024-06-22 18:10:09,490: INFO: stage_03_training_cross_val: *******************]
[2024-06-22 18:10:09,490: INFO: stage_03_training_cross_val: >>>>>> stage Training started <<<<<<]
[2024-06-22 18:10:09,492: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 18:10:09,494: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 18:10:09,495: INFO: common: created directory at: artifacts]
[2024-06-22 18:10:09,496: ERROR: stage_03_training_cross_val: "'ConfigBox' object has no attribute 'local_data_file'"]
Traceback (most recent call last):
  File "box/box.py", line 503, in box.box.Box.__getitem__
KeyError: 'local_data_file'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "box/box.py", line 536, in box.box.Box.__getattr__
  File "box/box.py", line 524, in box.box.Box.__getitem__
box.exceptions.BoxKeyError: "'local_data_file'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "box/box.py", line 538, in box.box.Box.__getattr__
AttributeError: 'ConfigBox' object has no attribute 'local_data_file'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "box/config_box.py", line 28, in box.config_box.ConfigBox.__getattr__
  File "box/box.py", line 552, in box.box.Box.__getattr__
box.exceptions.BoxKeyError: "'ConfigBox' object has no attribute 'local_data_file'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "box/box.py", line 503, in box.box.Box.__getitem__
KeyError: 'local_data_file'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "box/box.py", line 536, in box.box.Box.__getattr__
  File "box/box.py", line 524, in box.box.Box.__getitem__
box.exceptions.BoxKeyError: "'local_data_file'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "box/box.py", line 538, in box.box.Box.__getattr__
AttributeError: 'ConfigBox' object has no attribute 'local_data_file'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/nair.ro/mlops-model-dev/src/XGBClassifier/pipeline/stage_03_training_cross_val.py", line 30, in <module>
    obj.main()
  File "/home/nair.ro/mlops-model-dev/src/XGBClassifier/pipeline/stage_03_training_cross_val.py", line 16, in main
    training_config = config.get_training_config()
  File "/home/nair.ro/mlops-model-dev/src/XGBClassifier/config_mngr/configuration_manager.py", line 60, in get_training_config
    training_data = self.config.local_data_file
  File "box/config_box.py", line 30, in box.config_box.ConfigBox.__getattr__
  File "box/box.py", line 552, in box.box.Box.__getattr__
box.exceptions.BoxKeyError: "'ConfigBox' object has no attribute 'local_data_file'"
[2024-06-22 18:16:28,160: INFO: stage_03_training_cross_val: *******************]
[2024-06-22 18:16:28,160: INFO: stage_03_training_cross_val: >>>>>> stage Training started <<<<<<]
[2024-06-22 18:16:28,169: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 18:16:28,172: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 18:16:28,173: INFO: common: created directory at: artifacts]
[2024-06-22 18:16:28,173: ERROR: stage_03_training_cross_val: "'ConfigBox' object has no attribute 'local_data_file'"]
Traceback (most recent call last):
  File "box/box.py", line 503, in box.box.Box.__getitem__
KeyError: 'local_data_file'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "box/box.py", line 536, in box.box.Box.__getattr__
  File "box/box.py", line 524, in box.box.Box.__getitem__
box.exceptions.BoxKeyError: "'local_data_file'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "box/box.py", line 538, in box.box.Box.__getattr__
AttributeError: 'ConfigBox' object has no attribute 'local_data_file'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "box/config_box.py", line 28, in box.config_box.ConfigBox.__getattr__
  File "box/box.py", line 552, in box.box.Box.__getattr__
box.exceptions.BoxKeyError: "'ConfigBox' object has no attribute 'local_data_file'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "box/box.py", line 503, in box.box.Box.__getitem__
KeyError: 'local_data_file'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "box/box.py", line 536, in box.box.Box.__getattr__
  File "box/box.py", line 524, in box.box.Box.__getitem__
box.exceptions.BoxKeyError: "'local_data_file'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "box/box.py", line 538, in box.box.Box.__getattr__
AttributeError: 'ConfigBox' object has no attribute 'local_data_file'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/nair.ro/mlops-model-dev/src/XGBClassifier/pipeline/stage_03_training_cross_val.py", line 30, in <module>
    obj.main()
  File "/home/nair.ro/mlops-model-dev/src/XGBClassifier/pipeline/stage_03_training_cross_val.py", line 16, in main
    training_config = config.get_training_config()
  File "/home/nair.ro/mlops-model-dev/src/XGBClassifier/config_mngr/configuration_manager.py", line 60, in get_training_config
    training_data = self.config.local_data_file
  File "box/config_box.py", line 30, in box.config_box.ConfigBox.__getattr__
  File "box/box.py", line 552, in box.box.Box.__getattr__
box.exceptions.BoxKeyError: "'ConfigBox' object has no attribute 'local_data_file'"
[2024-06-22 18:18:59,007: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-06-22 18:18:59,010: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 18:18:59,012: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 18:18:59,014: INFO: common: created directory at: artifacts]
[2024-06-22 18:18:59,015: INFO: common: created directory at: artifacts/data_ingestion]
[2024-06-22 18:19:04,608: INFO: data_ingestion:  file from url https://drive.google.com/uc?/export=download&id=1RmDs2j3QcY05ixoV1-ACmxmnM5xdmiGF downloaded and saved at path artifacts/data_ingestion/card_transdata.csv]
[2024-06-22 18:19:04,624: INFO: data_ingestion:  File 'artifacts/data_ingestion/card_transdata.csv' is of type '.csv']
[2024-06-22 18:19:04,624: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-06-22 18:19:15,699: INFO: stage_02_prepare_base_model: *******************]
[2024-06-22 18:19:15,700: INFO: stage_02_prepare_base_model: >>>>>> stage Prepare base model started <<<<<<]
[2024-06-22 18:19:15,702: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 18:19:15,707: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 18:19:15,709: INFO: common: created directory at: artifacts]
[2024-06-22 18:19:15,710: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-06-22 18:19:15,710: INFO: prepare_base_model: Initialized XGBClassifier with following parameters PrepareBaseModelConfig(params_n_estimators=500, params_learning_rate=0.1, params_random_state=42, params_subsample=0.5, params_n_jobs=-1, params_max_depth=3)]
[2024-06-22 18:19:15,710: INFO: stage_02_prepare_base_model: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-06-22 18:19:23,864: INFO: stage_03_training_cross_val: *******************]
[2024-06-22 18:19:23,865: INFO: stage_03_training_cross_val: >>>>>> stage Training started <<<<<<]
[2024-06-22 18:19:23,867: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 18:19:23,873: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 18:19:23,875: INFO: common: created directory at: artifacts]
[2024-06-22 18:19:23,876: ERROR: stage_03_training_cross_val: "'ConfigBox' object has no attribute 'local_data_file'"]
Traceback (most recent call last):
  File "box/box.py", line 503, in box.box.Box.__getitem__
KeyError: 'local_data_file'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "box/box.py", line 536, in box.box.Box.__getattr__
  File "box/box.py", line 524, in box.box.Box.__getitem__
box.exceptions.BoxKeyError: "'local_data_file'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "box/box.py", line 538, in box.box.Box.__getattr__
AttributeError: 'ConfigBox' object has no attribute 'local_data_file'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "box/config_box.py", line 28, in box.config_box.ConfigBox.__getattr__
  File "box/box.py", line 552, in box.box.Box.__getattr__
box.exceptions.BoxKeyError: "'ConfigBox' object has no attribute 'local_data_file'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "box/box.py", line 503, in box.box.Box.__getitem__
KeyError: 'local_data_file'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "box/box.py", line 536, in box.box.Box.__getattr__
  File "box/box.py", line 524, in box.box.Box.__getitem__
box.exceptions.BoxKeyError: "'local_data_file'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "box/box.py", line 538, in box.box.Box.__getattr__
AttributeError: 'ConfigBox' object has no attribute 'local_data_file'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/nair.ro/mlops-model-dev/src/XGBClassifier/pipeline/stage_03_training_cross_val.py", line 30, in <module>
    obj.main()
  File "/home/nair.ro/mlops-model-dev/src/XGBClassifier/pipeline/stage_03_training_cross_val.py", line 16, in main
    training_config = config.get_training_config()
  File "/home/nair.ro/mlops-model-dev/src/XGBClassifier/config_mngr/configuration_manager.py", line 60, in get_training_config
    training_data = self.config.local_data_file
  File "box/config_box.py", line 30, in box.config_box.ConfigBox.__getattr__
  File "box/box.py", line 552, in box.box.Box.__getattr__
box.exceptions.BoxKeyError: "'ConfigBox' object has no attribute 'local_data_file'"
[2024-06-22 18:20:21,914: INFO: stage_03_training_cross_val: *******************]
[2024-06-22 18:20:21,914: INFO: stage_03_training_cross_val: >>>>>> stage Training started <<<<<<]
[2024-06-22 18:20:21,917: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 18:20:21,920: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 18:20:21,921: INFO: common: created directory at: artifacts]
[2024-06-22 18:20:21,921: ERROR: stage_03_training_cross_val: "'ConfigBox' object has no attribute 'local_data_file'"]
Traceback (most recent call last):
  File "box/box.py", line 503, in box.box.Box.__getitem__
KeyError: 'local_data_file'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "box/box.py", line 536, in box.box.Box.__getattr__
  File "box/box.py", line 524, in box.box.Box.__getitem__
box.exceptions.BoxKeyError: "'local_data_file'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "box/box.py", line 538, in box.box.Box.__getattr__
AttributeError: 'ConfigBox' object has no attribute 'local_data_file'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "box/config_box.py", line 28, in box.config_box.ConfigBox.__getattr__
  File "box/box.py", line 552, in box.box.Box.__getattr__
box.exceptions.BoxKeyError: "'ConfigBox' object has no attribute 'local_data_file'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "box/box.py", line 503, in box.box.Box.__getitem__
KeyError: 'local_data_file'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "box/box.py", line 536, in box.box.Box.__getattr__
  File "box/box.py", line 524, in box.box.Box.__getitem__
box.exceptions.BoxKeyError: "'local_data_file'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "box/box.py", line 538, in box.box.Box.__getattr__
AttributeError: 'ConfigBox' object has no attribute 'local_data_file'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/nair.ro/mlops-model-dev/src/XGBClassifier/pipeline/stage_03_training_cross_val.py", line 30, in <module>
    obj.main()
  File "/home/nair.ro/mlops-model-dev/src/XGBClassifier/pipeline/stage_03_training_cross_val.py", line 16, in main
    training_config = config.get_training_config()
  File "/home/nair.ro/mlops-model-dev/src/XGBClassifier/config_mngr/configuration_manager.py", line 60, in get_training_config
    training_data = self.config.local_data_file
  File "box/config_box.py", line 30, in box.config_box.ConfigBox.__getattr__
  File "box/box.py", line 552, in box.box.Box.__getattr__
box.exceptions.BoxKeyError: "'ConfigBox' object has no attribute 'local_data_file'"
[2024-06-22 18:22:52,234: INFO: stage_03_training_cross_val: *******************]
[2024-06-22 18:22:52,235: INFO: stage_03_training_cross_val: >>>>>> stage Training started <<<<<<]
[2024-06-22 18:22:52,238: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 18:22:52,242: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 18:22:52,243: INFO: common: created directory at: artifacts]
[2024-06-22 18:22:52,246: INFO: common: created directory at: artifacts/training]
[2024-06-22 18:22:52,247: ERROR: stage_03_training_cross_val: TrainingConfig.__init__() got an unexpected keyword argument 'params_scoring']
Traceback (most recent call last):
  File "/home/nair.ro/mlops-model-dev/src/XGBClassifier/pipeline/stage_03_training_cross_val.py", line 30, in <module>
    obj.main()
  File "/home/nair.ro/mlops-model-dev/src/XGBClassifier/pipeline/stage_03_training_cross_val.py", line 16, in main
    training_config = config.get_training_config()
  File "/home/nair.ro/mlops-model-dev/src/XGBClassifier/config_mngr/configuration_manager.py", line 65, in get_training_config
    training_config = TrainingConfig(
TypeError: TrainingConfig.__init__() got an unexpected keyword argument 'params_scoring'
[2024-06-22 18:22:57,488: INFO: stage_03_training_cross_val: *******************]
[2024-06-22 18:22:57,489: INFO: stage_03_training_cross_val: >>>>>> stage Training started <<<<<<]
[2024-06-22 18:22:57,491: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 18:22:57,493: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 18:22:57,493: INFO: common: created directory at: artifacts]
[2024-06-22 18:22:57,496: INFO: common: created directory at: artifacts/training]
[2024-06-22 18:22:57,496: ERROR: stage_03_training_cross_val: TrainingConfig.__init__() got an unexpected keyword argument 'params_scoring']
Traceback (most recent call last):
  File "/home/nair.ro/mlops-model-dev/src/XGBClassifier/pipeline/stage_03_training_cross_val.py", line 30, in <module>
    obj.main()
  File "/home/nair.ro/mlops-model-dev/src/XGBClassifier/pipeline/stage_03_training_cross_val.py", line 16, in main
    training_config = config.get_training_config()
  File "/home/nair.ro/mlops-model-dev/src/XGBClassifier/config_mngr/configuration_manager.py", line 65, in get_training_config
    training_config = TrainingConfig(
TypeError: TrainingConfig.__init__() got an unexpected keyword argument 'params_scoring'
[2024-06-22 18:23:50,914: INFO: stage_03_training_cross_val: *******************]
[2024-06-22 18:23:50,915: INFO: stage_03_training_cross_val: >>>>>> stage Training started <<<<<<]
[2024-06-22 18:23:50,921: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 18:23:50,926: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 18:23:50,927: INFO: common: created directory at: artifacts]
[2024-06-22 18:23:50,929: INFO: common: created directory at: artifacts/training]
[2024-06-22 18:23:50,929: ERROR: stage_03_training_cross_val: TrainingConfig.__init__() got an unexpected keyword argument 'params_cv']
Traceback (most recent call last):
  File "/home/nair.ro/mlops-model-dev/src/XGBClassifier/pipeline/stage_03_training_cross_val.py", line 30, in <module>
    obj.main()
  File "/home/nair.ro/mlops-model-dev/src/XGBClassifier/pipeline/stage_03_training_cross_val.py", line 16, in main
    training_config = config.get_training_config()
  File "/home/nair.ro/mlops-model-dev/src/XGBClassifier/config_mngr/configuration_manager.py", line 65, in get_training_config
    training_config = TrainingConfig(
TypeError: TrainingConfig.__init__() got an unexpected keyword argument 'params_cv'
[2024-06-22 18:26:05,550: INFO: stage_03_training_cross_val: *******************]
[2024-06-22 18:26:05,551: INFO: stage_03_training_cross_val: >>>>>> stage Training started <<<<<<]
[2024-06-22 18:26:05,557: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 18:26:05,561: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 18:26:05,562: INFO: common: created directory at: artifacts]
[2024-06-22 18:26:05,564: INFO: common: created directory at: artifacts/training]
[2024-06-22 18:26:05,565: ERROR: stage_03_training_cross_val: name 'xgb' is not defined]
Traceback (most recent call last):
  File "/home/nair.ro/mlops-model-dev/src/XGBClassifier/pipeline/stage_03_training_cross_val.py", line 30, in <module>
    obj.main()
  File "/home/nair.ro/mlops-model-dev/src/XGBClassifier/pipeline/stage_03_training_cross_val.py", line 19, in main
    training.train(xgb)
NameError: name 'xgb' is not defined
[2024-06-22 18:27:29,952: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-06-22 18:27:29,957: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 18:27:29,966: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 18:27:29,967: INFO: common: created directory at: artifacts]
[2024-06-22 18:27:29,972: INFO: common: created directory at: artifacts/data_ingestion]
[2024-06-22 18:27:29,974: INFO: data_ingestion: File already exists of size: ~ 74490 KB]
[2024-06-22 18:27:29,979: INFO: data_ingestion:  File 'artifacts/data_ingestion/card_transdata.csv' is of type '.csv']
[2024-06-22 18:27:29,979: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-06-22 18:27:29,980: INFO: main: *******************]
[2024-06-22 18:27:29,980: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-06-22 18:27:29,981: ERROR: main: name 'PrepareBaseModelTrainingPipeline' is not defined]
Traceback (most recent call last):
  File "/home/nair.ro/mlops-model-dev/main.py", line 23, in <module>
    prepare_base_model = PrepareBaseModelTrainingPipeline()
NameError: name 'PrepareBaseModelTrainingPipeline' is not defined
[2024-06-22 18:27:40,726: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-06-22 18:27:40,732: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 18:27:40,736: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 18:27:40,740: INFO: common: created directory at: artifacts]
[2024-06-22 18:27:40,742: INFO: common: created directory at: artifacts/data_ingestion]
[2024-06-22 18:27:40,743: INFO: data_ingestion: File already exists of size: ~ 74490 KB]
[2024-06-22 18:27:40,747: INFO: data_ingestion:  File 'artifacts/data_ingestion/card_transdata.csv' is of type '.csv']
[2024-06-22 18:27:40,747: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-06-22 18:27:40,748: INFO: main: *******************]
[2024-06-22 18:27:40,748: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-06-22 18:27:40,748: ERROR: main: name 'PrepareBaseModelTrainingPipeline' is not defined]
Traceback (most recent call last):
  File "/home/nair.ro/mlops-model-dev/main.py", line 23, in <module>
    prepare_base_model = PrepareBaseModelTrainingPipeline()
NameError: name 'PrepareBaseModelTrainingPipeline' is not defined
[2024-06-22 18:29:05,397: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-06-22 18:29:05,405: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 18:29:05,415: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 18:29:05,417: INFO: common: created directory at: artifacts]
[2024-06-22 18:29:05,422: INFO: common: created directory at: artifacts/data_ingestion]
[2024-06-22 18:29:05,425: INFO: data_ingestion: File already exists of size: ~ 74490 KB]
[2024-06-22 18:29:05,430: INFO: data_ingestion:  File 'artifacts/data_ingestion/card_transdata.csv' is of type '.csv']
[2024-06-22 18:29:05,433: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-06-22 18:29:05,434: INFO: main: *******************]
[2024-06-22 18:29:05,434: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-06-22 18:29:05,440: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 18:29:05,444: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 18:29:05,445: INFO: common: created directory at: artifacts]
[2024-06-22 18:29:05,447: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-06-22 18:29:05,448: INFO: prepare_base_model: Initialized XGBClassifier with following parameters PrepareBaseModelConfig(params_n_estimators=500, params_learning_rate=0.1, params_random_state=42, params_subsample=0.5, params_n_jobs=-1, params_max_depth=3)]
[2024-06-22 18:29:05,448: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-06-22 18:29:05,449: INFO: main: *******************]
[2024-06-22 18:29:05,449: INFO: main: >>>>>> stage Train and save model started <<<<<<]
[2024-06-22 18:29:05,452: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 18:29:05,457: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 18:29:05,459: INFO: common: created directory at: artifacts]
[2024-06-22 18:29:05,460: INFO: common: created directory at: artifacts/training]
[2024-06-22 18:29:05,461: ERROR: main: name 'train_valid_generator' is not defined]
Traceback (most recent call last):
  File "/home/nair.ro/mlops-model-dev/main.py", line 38, in <module>
    obj.main(xgb)
  File "/home/nair.ro/mlops-model-dev/src/XGBClassifier/pipeline/stage_03_training_cross_val.py", line 19, in main
    training.train(xgb)
  File "/home/nair.ro/mlops-model-dev/src/XGBClassifier/components/training.py", line 37, in train
    X_train , X_test ,y_train , y_test  = train_valid_generator()
NameError: name 'train_valid_generator' is not defined
[2024-06-22 18:30:40,463: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-06-22 18:30:40,471: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 18:30:40,477: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 18:30:40,480: INFO: common: created directory at: artifacts]
[2024-06-22 18:30:40,482: INFO: common: created directory at: artifacts/data_ingestion]
[2024-06-22 18:30:40,485: INFO: data_ingestion: File already exists of size: ~ 74490 KB]
[2024-06-22 18:30:40,489: INFO: data_ingestion:  File 'artifacts/data_ingestion/card_transdata.csv' is of type '.csv']
[2024-06-22 18:30:40,489: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-06-22 18:30:40,490: INFO: main: *******************]
[2024-06-22 18:30:40,490: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-06-22 18:30:40,493: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 18:30:40,496: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 18:30:40,497: INFO: common: created directory at: artifacts]
[2024-06-22 18:30:40,499: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-06-22 18:30:40,500: INFO: prepare_base_model: Initialized XGBClassifier with following parameters PrepareBaseModelConfig(params_n_estimators=500, params_learning_rate=0.1, params_random_state=42, params_subsample=0.5, params_n_jobs=-1, params_max_depth=3)]
[2024-06-22 18:30:40,500: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-06-22 18:30:40,500: INFO: main: *******************]
[2024-06-22 18:30:40,500: INFO: main: >>>>>> stage Train and save model started <<<<<<]
[2024-06-22 18:30:40,503: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 18:30:40,507: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 18:30:40,510: INFO: common: created directory at: artifacts]
[2024-06-22 18:30:40,512: INFO: common: created directory at: artifacts/training]
[2024-06-22 18:30:40,513: ERROR: main: name 'pd' is not defined]
Traceback (most recent call last):
  File "/home/nair.ro/mlops-model-dev/main.py", line 38, in <module>
    obj.main(xgb)
  File "/home/nair.ro/mlops-model-dev/src/XGBClassifier/pipeline/stage_03_training_cross_val.py", line 19, in main
    training.train(xgb)
  File "/home/nair.ro/mlops-model-dev/src/XGBClassifier/components/training.py", line 37, in train
    X_train , X_test ,y_train , y_test  = self.train_valid_generator()
  File "/home/nair.ro/mlops-model-dev/src/XGBClassifier/components/training.py", line 12, in train_valid_generator
    df = pd.read_csv(self.config.training_data,encoding='utf-8')
NameError: name 'pd' is not defined
[2024-06-22 18:31:05,232: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-06-22 18:31:05,237: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 18:31:05,241: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 18:31:05,242: INFO: common: created directory at: artifacts]
[2024-06-22 18:31:05,243: INFO: common: created directory at: artifacts/data_ingestion]
[2024-06-22 18:31:05,244: INFO: data_ingestion: File already exists of size: ~ 74490 KB]
[2024-06-22 18:31:05,245: INFO: data_ingestion:  File 'artifacts/data_ingestion/card_transdata.csv' is of type '.csv']
[2024-06-22 18:31:05,246: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-06-22 18:31:05,246: INFO: main: *******************]
[2024-06-22 18:31:05,246: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-06-22 18:31:05,250: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 18:31:05,252: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 18:31:05,254: INFO: common: created directory at: artifacts]
[2024-06-22 18:31:05,255: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-06-22 18:31:05,255: INFO: prepare_base_model: Initialized XGBClassifier with following parameters PrepareBaseModelConfig(params_n_estimators=500, params_learning_rate=0.1, params_random_state=42, params_subsample=0.5, params_n_jobs=-1, params_max_depth=3)]
[2024-06-22 18:31:05,256: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-06-22 18:31:05,256: INFO: main: *******************]
[2024-06-22 18:31:05,256: INFO: main: >>>>>> stage Train and save model started <<<<<<]
[2024-06-22 18:31:05,259: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 18:31:05,263: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 18:31:05,263: INFO: common: created directory at: artifacts]
[2024-06-22 18:31:05,264: INFO: common: created directory at: artifacts/training]
[2024-06-22 18:31:06,260: ERROR: main: name 'train_test_split' is not defined]
Traceback (most recent call last):
  File "/home/nair.ro/mlops-model-dev/main.py", line 38, in <module>
    obj.main(xgb)
  File "/home/nair.ro/mlops-model-dev/src/XGBClassifier/pipeline/stage_03_training_cross_val.py", line 19, in main
    training.train(xgb)
  File "/home/nair.ro/mlops-model-dev/src/XGBClassifier/components/training.py", line 37, in train
    X_train , X_test ,y_train , y_test  = self.train_valid_generator()
  File "/home/nair.ro/mlops-model-dev/src/XGBClassifier/components/training.py", line 18, in train_valid_generator
    X_train , X_test ,y_train , y_test = train_test_split(X,y,test_size = 0.2 ,random_state = 42 ,stratify=y)
NameError: name 'train_test_split' is not defined
[2024-06-22 18:31:39,666: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-06-22 18:31:39,669: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 18:31:39,670: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 18:31:39,672: INFO: common: created directory at: artifacts]
[2024-06-22 18:31:39,673: INFO: common: created directory at: artifacts/data_ingestion]
[2024-06-22 18:31:39,673: INFO: data_ingestion: File already exists of size: ~ 74490 KB]
[2024-06-22 18:31:39,675: INFO: data_ingestion:  File 'artifacts/data_ingestion/card_transdata.csv' is of type '.csv']
[2024-06-22 18:31:39,675: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-06-22 18:31:39,675: INFO: main: *******************]
[2024-06-22 18:31:39,676: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-06-22 18:31:39,679: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 18:31:39,681: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 18:31:39,682: INFO: common: created directory at: artifacts]
[2024-06-22 18:31:39,687: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-06-22 18:31:39,687: INFO: prepare_base_model: Initialized XGBClassifier with following parameters PrepareBaseModelConfig(params_n_estimators=500, params_learning_rate=0.1, params_random_state=42, params_subsample=0.5, params_n_jobs=-1, params_max_depth=3)]
[2024-06-22 18:31:39,687: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-06-22 18:31:39,688: INFO: main: *******************]
[2024-06-22 18:31:39,688: INFO: main: >>>>>> stage Train and save model started <<<<<<]
[2024-06-22 18:31:39,691: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 18:31:39,693: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 18:31:39,694: INFO: common: created directory at: artifacts]
[2024-06-22 18:31:39,695: INFO: common: created directory at: artifacts/training]
[2024-06-22 18:31:41,008: ERROR: main: name 'logger' is not defined]
Traceback (most recent call last):
  File "/home/nair.ro/mlops-model-dev/main.py", line 38, in <module>
    obj.main(xgb)
  File "/home/nair.ro/mlops-model-dev/src/XGBClassifier/pipeline/stage_03_training_cross_val.py", line 19, in main
    training.train(xgb)
  File "/home/nair.ro/mlops-model-dev/src/XGBClassifier/components/training.py", line 40, in train
    logger.info(f"Model training and cross validation initiated.")
NameError: name 'logger' is not defined
[2024-06-22 18:32:37,411: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-06-22 18:32:37,414: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 18:32:37,416: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 18:32:37,417: INFO: common: created directory at: artifacts]
[2024-06-22 18:32:37,418: INFO: common: created directory at: artifacts/data_ingestion]
[2024-06-22 18:32:37,419: INFO: data_ingestion: File already exists of size: ~ 74490 KB]
[2024-06-22 18:32:37,420: INFO: data_ingestion:  File 'artifacts/data_ingestion/card_transdata.csv' is of type '.csv']
[2024-06-22 18:32:37,420: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-06-22 18:32:37,420: INFO: main: *******************]
[2024-06-22 18:32:37,420: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-06-22 18:32:37,422: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 18:32:37,424: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 18:32:37,425: INFO: common: created directory at: artifacts]
[2024-06-22 18:32:37,426: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-06-22 18:32:37,426: INFO: prepare_base_model: Initialized XGBClassifier with following parameters PrepareBaseModelConfig(params_n_estimators=500, params_learning_rate=0.1, params_random_state=42, params_subsample=0.5, params_n_jobs=-1, params_max_depth=3)]
[2024-06-22 18:32:37,426: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-06-22 18:32:37,426: INFO: main: *******************]
[2024-06-22 18:32:37,426: INFO: main: >>>>>> stage Train and save model started <<<<<<]
[2024-06-22 18:32:37,429: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 18:32:37,430: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 18:32:37,431: INFO: common: created directory at: artifacts]
[2024-06-22 18:32:37,432: INFO: common: created directory at: artifacts/training]
[2024-06-22 18:32:38,680: INFO: training: Model training and cross validation initiated.]
[2024-06-22 18:32:38,680: ERROR: main: name 'validate' is not defined]
Traceback (most recent call last):
  File "/home/nair.ro/mlops-model-dev/main.py", line 38, in <module>
    obj.main(xgb)
  File "/home/nair.ro/mlops-model-dev/src/XGBClassifier/pipeline/stage_03_training_cross_val.py", line 19, in main
    training.train(xgb)
  File "/home/nair.ro/mlops-model-dev/src/XGBClassifier/components/training.py", line 42, in train
    model = validate( xgb  ,X_train,y_train, self.config.params_scoring ,self.config.params_cv)
NameError: name 'validate' is not defined
[2024-06-22 18:33:16,252: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-06-22 18:33:16,255: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 18:33:16,261: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 18:33:16,262: INFO: common: created directory at: artifacts]
[2024-06-22 18:33:16,263: INFO: common: created directory at: artifacts/data_ingestion]
[2024-06-22 18:33:16,263: INFO: data_ingestion: File already exists of size: ~ 74490 KB]
[2024-06-22 18:33:16,265: INFO: data_ingestion:  File 'artifacts/data_ingestion/card_transdata.csv' is of type '.csv']
[2024-06-22 18:33:16,265: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-06-22 18:33:16,265: INFO: main: *******************]
[2024-06-22 18:33:16,266: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-06-22 18:33:16,268: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 18:33:16,271: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 18:33:16,272: INFO: common: created directory at: artifacts]
[2024-06-22 18:33:16,272: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-06-22 18:33:16,272: INFO: prepare_base_model: Initialized XGBClassifier with following parameters PrepareBaseModelConfig(params_n_estimators=500, params_learning_rate=0.1, params_random_state=42, params_subsample=0.5, params_n_jobs=-1, params_max_depth=3)]
[2024-06-22 18:33:16,273: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-06-22 18:33:16,273: INFO: main: *******************]
[2024-06-22 18:33:16,273: INFO: main: >>>>>> stage Train and save model started <<<<<<]
[2024-06-22 18:33:16,276: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 18:33:16,278: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 18:33:16,279: INFO: common: created directory at: artifacts]
[2024-06-22 18:33:16,280: INFO: common: created directory at: artifacts/training]
[2024-06-22 18:33:17,659: INFO: training: Model training and cross validation initiated.]
[2024-06-22 18:33:17,660: ERROR: main: 'TrainingConfig' object has no attribute 'params_scoring']
Traceback (most recent call last):
  File "/home/nair.ro/mlops-model-dev/main.py", line 38, in <module>
    obj.main(xgb)
  File "/home/nair.ro/mlops-model-dev/src/XGBClassifier/pipeline/stage_03_training_cross_val.py", line 19, in main
    training.train(xgb)
  File "/home/nair.ro/mlops-model-dev/src/XGBClassifier/components/training.py", line 42, in train
    model = self.validate( xgb  ,X_train,y_train, self.config.params_scoring ,self.config.params_cv)
AttributeError: 'TrainingConfig' object has no attribute 'params_scoring'
[2024-06-22 18:34:38,721: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-06-22 18:34:38,724: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 18:34:38,726: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 18:34:38,727: INFO: common: created directory at: artifacts]
[2024-06-22 18:34:38,728: INFO: common: created directory at: artifacts/data_ingestion]
[2024-06-22 18:34:38,729: INFO: data_ingestion: File already exists of size: ~ 74490 KB]
[2024-06-22 18:34:38,730: INFO: data_ingestion:  File 'artifacts/data_ingestion/card_transdata.csv' is of type '.csv']
[2024-06-22 18:34:38,730: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-06-22 18:34:38,730: INFO: main: *******************]
[2024-06-22 18:34:38,730: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-06-22 18:34:38,734: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 18:34:38,736: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 18:34:38,736: INFO: common: created directory at: artifacts]
[2024-06-22 18:34:38,737: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-06-22 18:34:38,737: INFO: prepare_base_model: Initialized XGBClassifier with following parameters PrepareBaseModelConfig(params_n_estimators=500, params_learning_rate=0.1, params_random_state=42, params_subsample=0.5, params_n_jobs=-1, params_max_depth=3)]
[2024-06-22 18:34:38,738: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-06-22 18:34:38,738: INFO: main: *******************]
[2024-06-22 18:34:38,738: INFO: main: >>>>>> stage Train and save model started <<<<<<]
[2024-06-22 18:34:38,740: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 18:34:38,743: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 18:34:38,743: INFO: common: created directory at: artifacts]
[2024-06-22 18:34:38,744: INFO: common: created directory at: artifacts/training]
[2024-06-22 18:34:40,293: INFO: training: Model training and cross validation initiated.]
[2024-06-22 18:34:40,293: ERROR: main: Training.validate() takes 5 positional arguments but 6 were given]
Traceback (most recent call last):
  File "/home/nair.ro/mlops-model-dev/main.py", line 38, in <module>
    obj.main(xgb)
  File "/home/nair.ro/mlops-model-dev/src/XGBClassifier/pipeline/stage_03_training_cross_val.py", line 19, in main
    training.train(xgb)
  File "/home/nair.ro/mlops-model-dev/src/XGBClassifier/components/training.py", line 42, in train
    model = self.validate( xgb  ,X_train,y_train, self.config.scoring ,self.config.cv)
TypeError: Training.validate() takes 5 positional arguments but 6 were given
[2024-06-22 18:36:34,207: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-06-22 18:36:34,210: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 18:36:34,213: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 18:36:34,214: INFO: common: created directory at: artifacts]
[2024-06-22 18:36:34,215: INFO: common: created directory at: artifacts/data_ingestion]
[2024-06-22 18:36:34,219: INFO: data_ingestion: File already exists of size: ~ 74490 KB]
[2024-06-22 18:36:34,220: INFO: data_ingestion:  File 'artifacts/data_ingestion/card_transdata.csv' is of type '.csv']
[2024-06-22 18:36:34,221: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-06-22 18:36:34,221: INFO: main: *******************]
[2024-06-22 18:36:34,221: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-06-22 18:36:34,223: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 18:36:34,225: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 18:36:34,226: INFO: common: created directory at: artifacts]
[2024-06-22 18:36:34,231: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-06-22 18:36:34,231: INFO: prepare_base_model: Initialized XGBClassifier with following parameters PrepareBaseModelConfig(params_n_estimators=500, params_learning_rate=0.1, params_random_state=42, params_subsample=0.5, params_n_jobs=-1, params_max_depth=3)]
[2024-06-22 18:36:34,232: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-06-22 18:36:34,232: INFO: main: *******************]
[2024-06-22 18:36:34,232: INFO: main: >>>>>> stage Train and save model started <<<<<<]
[2024-06-22 18:36:34,235: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 18:36:34,240: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 18:36:34,242: INFO: common: created directory at: artifacts]
[2024-06-22 18:36:34,242: INFO: common: created directory at: artifacts/training]
[2024-06-22 18:36:35,618: INFO: training: Model training and cross validation initiated.]
[2024-06-22 18:38:21,264: INFO: training: Cross Validation Scores: [0.99063215 0.98941648 0.9902746  0.98820164 0.98905971]]
[2024-06-22 18:38:21,265: INFO: training: Scores Mean:  0.9895169155985206]
[2024-06-22 18:38:21,265: INFO: training: Scores Standard Deviation: 0.0008679747406873597]
[2024-06-22 18:38:44,916: INFO: training: Model saved in path artifacts/training/model.pkl.]
[2024-06-22 18:38:44,917: INFO: main: >>>>>> stage Train and save model completed <<<<<<

x==========x]
[2024-06-22 19:03:51,361: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-06-22 19:03:51,365: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 19:03:51,369: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 19:03:51,373: INFO: common: created directory at: artifacts]
[2024-06-22 19:03:51,377: INFO: common: created directory at: artifacts/data_ingestion]
[2024-06-22 19:03:55,699: INFO: data_ingestion:  file from url https://drive.google.com/uc?/export=download&id=1RmDs2j3QcY05ixoV1-ACmxmnM5xdmiGF downloaded and saved at path artifacts/data_ingestion/card_transdata.csv]
[2024-06-22 19:03:55,713: INFO: data_ingestion:  File 'artifacts/data_ingestion/card_transdata.csv' is of type '.csv']
[2024-06-22 19:03:55,713: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-06-22 19:03:55,713: INFO: main: *******************]
[2024-06-22 19:03:55,714: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-06-22 19:03:55,717: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 19:03:55,719: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 19:03:55,720: INFO: common: created directory at: artifacts]
[2024-06-22 19:03:55,723: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-06-22 19:03:55,724: INFO: prepare_base_model: Initialized XGBClassifier with following parameters PrepareBaseModelConfig(params_n_estimators=500, params_learning_rate=0.1, params_random_state=42, params_subsample=0.5, params_n_jobs=-1, params_max_depth=3)]
[2024-06-22 19:03:55,724: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-06-22 19:03:55,725: INFO: main: *******************]
[2024-06-22 19:03:55,726: INFO: main: >>>>>> stage Train and save model started <<<<<<]
[2024-06-22 19:03:55,728: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 19:03:55,731: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 19:03:55,732: INFO: common: created directory at: artifacts]
[2024-06-22 19:03:55,734: INFO: common: created directory at: artifacts/training]
[2024-06-22 19:03:55,735: ERROR: main: TrainingConfig.__init__() missing 2 required positional arguments: 'stratify' and 'test_size']
Traceback (most recent call last):
  File "/home/nair.ro/mlops-model-dev/main.py", line 38, in <module>
    obj.main(xgb)
  File "/home/nair.ro/mlops-model-dev/src/XGBClassifier/pipeline/stage_03_training_cross_val.py", line 16, in main
    training_config = config.get_training_config()
  File "/home/nair.ro/mlops-model-dev/src/XGBClassifier/config_mngr/configuration_manager.py", line 63, in get_training_config
    training_config = TrainingConfig(
TypeError: TrainingConfig.__init__() missing 2 required positional arguments: 'stratify' and 'test_size'
[2024-06-22 19:04:55,013: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-06-22 19:04:55,016: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 19:04:55,018: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 19:04:55,020: INFO: common: created directory at: artifacts]
[2024-06-22 19:04:55,022: INFO: common: created directory at: artifacts/data_ingestion]
[2024-06-22 19:04:55,023: INFO: data_ingestion: File already exists of size: ~ 74490 KB]
[2024-06-22 19:04:55,025: INFO: data_ingestion:  File 'artifacts/data_ingestion/card_transdata.csv' is of type '.csv']
[2024-06-22 19:04:55,025: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-06-22 19:04:55,025: INFO: main: *******************]
[2024-06-22 19:04:55,026: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-06-22 19:04:55,028: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 19:04:55,031: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 19:04:55,032: INFO: common: created directory at: artifacts]
[2024-06-22 19:04:55,033: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-06-22 19:04:55,033: INFO: prepare_base_model: Initialized XGBClassifier with following parameters PrepareBaseModelConfig(params_n_estimators=500, params_learning_rate=0.1, params_random_state=42, params_subsample=0.5, params_n_jobs=-1, params_max_depth=3)]
[2024-06-22 19:04:55,033: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-06-22 19:04:55,033: INFO: main: *******************]
[2024-06-22 19:04:55,034: INFO: main: >>>>>> stage Train and save model started <<<<<<]
[2024-06-22 19:04:55,036: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 19:04:55,041: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 19:04:55,041: INFO: common: created directory at: artifacts]
[2024-06-22 19:04:55,042: INFO: common: created directory at: artifacts/training]
[2024-06-22 19:04:55,983: ERROR: main: 'TrainingConfig' object has no attribute 'random_state']
Traceback (most recent call last):
  File "/home/nair.ro/mlops-model-dev/main.py", line 38, in <module>
    obj.main(xgb)
  File "/home/nair.ro/mlops-model-dev/src/XGBClassifier/pipeline/stage_03_training_cross_val.py", line 19, in main
    training.train(xgb)
  File "/home/nair.ro/mlops-model-dev/src/XGBClassifier/components/training.py", line 40, in train
    X_train , X_test ,y_train , y_test  = self.train_valid_generator()
  File "/home/nair.ro/mlops-model-dev/src/XGBClassifier/components/training.py", line 21, in train_valid_generator
    X_train , X_test ,y_train , y_test = train_test_split(X,y,test_size = self.config.test_size ,random_state =self.config.random_state  ,stratify=self.config.stratify)
AttributeError: 'TrainingConfig' object has no attribute 'random_state'
[2024-06-22 19:05:46,012: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-06-22 19:05:46,015: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 19:05:46,017: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 19:05:46,019: INFO: common: created directory at: artifacts]
[2024-06-22 19:05:46,020: INFO: common: created directory at: artifacts/data_ingestion]
[2024-06-22 19:05:46,022: INFO: data_ingestion: File already exists of size: ~ 74490 KB]
[2024-06-22 19:05:46,024: INFO: data_ingestion:  File 'artifacts/data_ingestion/card_transdata.csv' is of type '.csv']
[2024-06-22 19:05:46,024: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-06-22 19:05:46,025: INFO: main: *******************]
[2024-06-22 19:05:46,025: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-06-22 19:05:46,027: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 19:05:46,030: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 19:05:46,030: INFO: common: created directory at: artifacts]
[2024-06-22 19:05:46,031: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-06-22 19:05:46,031: INFO: prepare_base_model: Initialized XGBClassifier with following parameters PrepareBaseModelConfig(params_n_estimators=500, params_learning_rate=0.1, params_random_state=42, params_subsample=0.5, params_n_jobs=-1, params_max_depth=3)]
[2024-06-22 19:05:46,032: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-06-22 19:05:46,032: INFO: main: *******************]
[2024-06-22 19:05:46,032: INFO: main: >>>>>> stage Train and save model started <<<<<<]
[2024-06-22 19:05:46,036: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 19:05:46,037: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 19:05:46,038: INFO: common: created directory at: artifacts]
[2024-06-22 19:05:46,039: INFO: common: created directory at: artifacts/training]
[2024-06-22 19:05:46,039: ERROR: main: TrainingConfig.__init__() got an unexpected keyword argument 'random_state']
Traceback (most recent call last):
  File "/home/nair.ro/mlops-model-dev/main.py", line 38, in <module>
    obj.main(xgb)
  File "/home/nair.ro/mlops-model-dev/src/XGBClassifier/pipeline/stage_03_training_cross_val.py", line 16, in main
    training_config = config.get_training_config()
  File "/home/nair.ro/mlops-model-dev/src/XGBClassifier/config_mngr/configuration_manager.py", line 63, in get_training_config
    training_config = TrainingConfig(
TypeError: TrainingConfig.__init__() got an unexpected keyword argument 'random_state'
[2024-06-22 19:08:44,289: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-06-22 19:08:44,291: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 19:08:44,293: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 19:08:44,295: INFO: common: created directory at: artifacts]
[2024-06-22 19:08:44,296: INFO: common: created directory at: artifacts/data_ingestion]
[2024-06-22 19:08:44,297: INFO: data_ingestion: File already exists of size: ~ 74490 KB]
[2024-06-22 19:08:44,298: INFO: data_ingestion:  File 'artifacts/data_ingestion/card_transdata.csv' is of type '.csv']
[2024-06-22 19:08:44,298: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-06-22 19:08:44,299: INFO: main: *******************]
[2024-06-22 19:08:44,299: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-06-22 19:08:44,301: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 19:08:44,303: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 19:08:44,304: INFO: common: created directory at: artifacts]
[2024-06-22 19:08:44,305: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-06-22 19:08:44,305: INFO: prepare_base_model: Initialized XGBClassifier with following parameters PrepareBaseModelConfig(params_n_estimators=500, params_learning_rate=0.1, params_random_state=42, params_subsample=0.5, params_n_jobs=-1, params_max_depth=3)]
[2024-06-22 19:08:44,305: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-06-22 19:08:44,305: INFO: main: *******************]
[2024-06-22 19:08:44,305: INFO: main: >>>>>> stage Train and save model started <<<<<<]
[2024-06-22 19:08:44,308: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 19:08:44,310: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 19:08:44,311: INFO: common: created directory at: artifacts]
[2024-06-22 19:08:44,312: INFO: common: created directory at: artifacts/training]
[2024-06-22 19:08:45,192: ERROR: main: The 'stratify' parameter of train_test_split must be an array-like or None. Got 'y' instead.]
Traceback (most recent call last):
  File "/home/nair.ro/mlops-model-dev/main.py", line 38, in <module>
    obj.main(xgb)
  File "/home/nair.ro/mlops-model-dev/src/XGBClassifier/pipeline/stage_03_training_cross_val.py", line 19, in main
    training.train(xgb)
  File "/home/nair.ro/mlops-model-dev/src/XGBClassifier/components/training.py", line 40, in train
    X_train , X_test ,y_train , y_test  = self.train_valid_generator()
  File "/home/nair.ro/mlops-model-dev/src/XGBClassifier/components/training.py", line 21, in train_valid_generator
    X_train , X_test ,y_train , y_test = train_test_split(X,y,test_size = self.config.test_size ,random_state =self.config.random_state  ,stratify=self.config.stratify)
  File "/home/nair.ro/miniforge3/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 203, in wrapper
    validate_parameter_constraints(
  File "/home/nair.ro/miniforge3/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'stratify' parameter of train_test_split must be an array-like or None. Got 'y' instead.
[2024-06-22 19:11:26,363: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-06-22 19:11:26,365: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 19:11:26,368: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 19:11:26,369: INFO: common: created directory at: artifacts]
[2024-06-22 19:11:26,369: INFO: common: created directory at: artifacts/data_ingestion]
[2024-06-22 19:11:26,370: INFO: data_ingestion: File already exists of size: ~ 74490 KB]
[2024-06-22 19:11:26,372: INFO: data_ingestion:  File 'artifacts/data_ingestion/card_transdata.csv' is of type '.csv']
[2024-06-22 19:11:26,372: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-06-22 19:11:26,372: INFO: main: *******************]
[2024-06-22 19:11:26,372: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-06-22 19:11:26,376: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 19:11:26,377: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 19:11:26,380: INFO: common: created directory at: artifacts]
[2024-06-22 19:11:26,381: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-06-22 19:11:26,381: INFO: prepare_base_model: Initialized XGBClassifier with following parameters PrepareBaseModelConfig(params_n_estimators=500, params_learning_rate=0.1, params_random_state=42, params_subsample=0.5, params_n_jobs=-1, params_max_depth=3)]
[2024-06-22 19:11:26,381: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-06-22 19:11:26,382: INFO: main: *******************]
[2024-06-22 19:11:26,382: INFO: main: >>>>>> stage Train and save model started <<<<<<]
[2024-06-22 19:11:26,384: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 19:11:26,387: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 19:11:26,387: INFO: common: created directory at: artifacts]
[2024-06-22 19:11:26,388: INFO: common: created directory at: artifacts/training]
[2024-06-22 19:11:27,649: INFO: training: Model training and cross validation initiated.]
[2024-06-22 19:13:17,737: INFO: training: Cross Validation Scores: [0.99063215 0.98941648 0.9902746  0.98820164 0.98905971]]
[2024-06-22 19:13:17,738: INFO: training: Scores Mean:  0.9895169155985206]
[2024-06-22 19:13:17,739: INFO: training: Scores Standard Deviation: 0.0008679747406873597]
[2024-06-22 19:13:47,031: INFO: training: Model saved in path artifacts/training/model.pkl.]
[2024-06-22 19:13:47,032: INFO: main: >>>>>> stage Train and save model completed <<<<<<

x==========x]
[2024-06-22 19:43:11,275: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-06-22 19:43:11,279: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 19:43:11,283: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 19:43:11,283: INFO: common: created directory at: artifacts]
[2024-06-22 19:43:11,284: INFO: common: created directory at: artifacts/data_ingestion]
[2024-06-22 19:43:11,285: INFO: data_ingestion: File already exists of size: ~ 74490 KB]
[2024-06-22 19:43:11,286: INFO: data_ingestion:  File 'artifacts/data_ingestion/card_transdata.csv' is of type '.csv']
[2024-06-22 19:43:11,286: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-06-22 19:43:11,286: INFO: main: *******************]
[2024-06-22 19:43:11,287: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-06-22 19:43:11,290: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 19:43:11,292: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 19:43:11,292: INFO: common: created directory at: artifacts]
[2024-06-22 19:43:11,293: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-06-22 19:43:11,293: INFO: prepare_base_model: Initialized XGBClassifier with following parameters PrepareBaseModelConfig(params_n_estimators=500, params_learning_rate=0.1, params_random_state=42, params_subsample=0.5, params_n_jobs=-1, params_max_depth=3)]
[2024-06-22 19:43:11,293: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-06-22 19:43:11,294: INFO: main: *******************]
[2024-06-22 19:43:11,294: INFO: main: >>>>>> stage Train and save model started <<<<<<]
[2024-06-22 19:43:11,297: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 19:43:11,299: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 19:43:11,300: INFO: common: created directory at: artifacts]
[2024-06-22 19:43:11,301: INFO: common: created directory at: artifacts/training]
[2024-06-22 19:43:12,694: INFO: training: Model training and cross validation initiated.]
[2024-06-22 19:44:57,939: INFO: training: Cross Validation Scores: [0.99063215 0.98941648 0.9902746  0.98820164 0.98905971]]
[2024-06-22 19:44:57,940: INFO: training: Scores Mean:  0.9895169155985206]
[2024-06-22 19:44:57,940: INFO: training: Scores Standard Deviation: 0.0008679747406873597]
[2024-06-22 19:45:21,836: INFO: training: Model saved in path artifacts/training/model.pkl.]
[2024-06-22 19:45:21,837: INFO: main: >>>>>> stage Train and save model completed <<<<<<

x==========x]
[2024-06-22 19:45:21,837: INFO: main: *******************]
[2024-06-22 19:45:21,837: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-06-22 19:45:21,837: ERROR: main: name 'EvaluationPipeline' is not defined]
Traceback (most recent call last):
  File "/home/nair.ro/mlops-model-dev/main.py", line 51, in <module>
    model_evalution = EvaluationPipeline()
NameError: name 'EvaluationPipeline' is not defined
[2024-06-22 19:52:25,482: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-06-22 19:52:25,489: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 19:52:25,493: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 19:52:25,494: INFO: common: created directory at: artifacts]
[2024-06-22 19:52:25,495: INFO: common: created directory at: artifacts/data_ingestion]
[2024-06-22 19:52:25,497: INFO: data_ingestion: File already exists of size: ~ 74490 KB]
[2024-06-22 19:52:25,500: INFO: data_ingestion:  File 'artifacts/data_ingestion/card_transdata.csv' is of type '.csv']
[2024-06-22 19:52:25,500: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-06-22 19:52:25,501: INFO: main: *******************]
[2024-06-22 19:52:25,502: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-06-22 19:52:25,506: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 19:52:25,509: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 19:52:25,511: INFO: common: created directory at: artifacts]
[2024-06-22 19:52:25,513: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-06-22 19:52:25,513: INFO: prepare_base_model: Initialized XGBClassifier with following parameters PrepareBaseModelConfig(params_n_estimators=500, params_learning_rate=0.1, params_random_state=42, params_subsample=0.5, params_n_jobs=-1, params_max_depth=3)]
[2024-06-22 19:52:25,513: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-06-22 19:52:25,514: INFO: main: *******************]
[2024-06-22 19:52:25,514: INFO: main: >>>>>> stage Train and save model started <<<<<<]
[2024-06-22 19:52:25,519: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 19:52:25,522: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 19:52:25,523: INFO: common: created directory at: artifacts]
[2024-06-22 19:52:25,527: INFO: common: created directory at: artifacts/training]
[2024-06-22 19:52:27,250: INFO: training: Model training and cross validation initiated.]
[2024-06-22 19:54:13,200: INFO: training: Cross Validation Scores: [0.99063215 0.98941648 0.9902746  0.98820164 0.98905971]]
[2024-06-22 19:54:13,203: INFO: training: Scores Mean:  0.9895169155985206]
[2024-06-22 19:54:13,203: INFO: training: Scores Standard Deviation: 0.0008679747406873597]
[2024-06-22 19:54:37,229: INFO: training: Model saved in path artifacts/training/model.pkl.]
[2024-06-22 19:54:37,232: INFO: main: >>>>>> stage Train and save model completed <<<<<<

x==========x]
[2024-06-22 19:54:37,232: INFO: main: *******************]
[2024-06-22 19:54:37,232: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-06-22 19:54:37,232: ERROR: main: name 'model_evaluation' is not defined]
Traceback (most recent call last):
  File "/home/nair.ro/mlops-model-dev/main.py", line 52, in <module>
    model_evalution.main(xgb)
  File "/home/nair.ro/mlops-model-dev/src/XGBClassifier/pipeline/stage_04_evaluation.py", line 15, in main
    model_evaluation(xgb)
NameError: name 'model_evaluation' is not defined
[2024-06-22 19:57:30,148: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-06-22 19:57:30,152: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 19:57:30,156: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 19:57:30,157: INFO: common: created directory at: artifacts]
[2024-06-22 19:57:30,159: INFO: common: created directory at: artifacts/data_ingestion]
[2024-06-22 19:57:30,160: INFO: data_ingestion: File already exists of size: ~ 74490 KB]
[2024-06-22 19:57:30,161: INFO: data_ingestion:  File 'artifacts/data_ingestion/card_transdata.csv' is of type '.csv']
[2024-06-22 19:57:30,161: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-06-22 19:57:30,162: INFO: main: *******************]
[2024-06-22 19:57:30,162: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-06-22 19:57:30,165: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 19:57:30,167: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 19:57:30,173: INFO: common: created directory at: artifacts]
[2024-06-22 19:57:30,173: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-06-22 19:57:30,174: INFO: prepare_base_model: Initialized XGBClassifier with following parameters PrepareBaseModelConfig(params_n_estimators=500, params_learning_rate=0.1, params_random_state=42, params_subsample=0.5, params_n_jobs=-1, params_max_depth=3)]
[2024-06-22 19:57:30,174: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-06-22 19:57:30,174: INFO: main: *******************]
[2024-06-22 19:57:30,175: INFO: main: >>>>>> stage Train and save model started <<<<<<]
[2024-06-22 19:57:30,177: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 19:57:30,180: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 19:57:30,181: INFO: common: created directory at: artifacts]
[2024-06-22 19:57:30,181: INFO: common: created directory at: artifacts/training]
[2024-06-22 19:57:31,449: INFO: training: Model training and cross validation initiated.]
[2024-06-22 19:59:17,079: INFO: training: Cross Validation Scores: [0.99063215 0.98941648 0.9902746  0.98820164 0.98905971]]
[2024-06-22 19:59:17,080: INFO: training: Scores Mean:  0.9895169155985206]
[2024-06-22 19:59:17,081: INFO: training: Scores Standard Deviation: 0.0008679747406873597]
[2024-06-22 19:59:41,565: INFO: training: Model saved in path artifacts/training/model.pkl.]
[2024-06-22 19:59:41,566: INFO: main: >>>>>> stage Train and save model completed <<<<<<

x==========x]
[2024-06-22 19:59:41,566: INFO: main: *******************]
[2024-06-22 19:59:41,566: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-06-22 19:59:41,567: ERROR: main: name 'model_evaluation' is not defined]
Traceback (most recent call last):
  File "/home/nair.ro/mlops-model-dev/main.py", line 52, in <module>
    model_evalution.main(xgb)
  File "/home/nair.ro/mlops-model-dev/src/XGBClassifier/pipeline/stage_04_evaluation.py", line 17, in main
    model_evaluation(xgb)
NameError: name 'model_evaluation' is not defined
[2024-06-22 20:00:43,869: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-06-22 20:00:43,872: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 20:00:43,876: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 20:00:43,877: INFO: common: created directory at: artifacts]
[2024-06-22 20:00:43,882: INFO: common: created directory at: artifacts/data_ingestion]
[2024-06-22 20:00:43,883: INFO: data_ingestion: File already exists of size: ~ 74490 KB]
[2024-06-22 20:00:43,885: INFO: data_ingestion:  File 'artifacts/data_ingestion/card_transdata.csv' is of type '.csv']
[2024-06-22 20:00:43,885: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-06-22 20:00:43,886: INFO: main: *******************]
[2024-06-22 20:00:43,886: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-06-22 20:00:43,890: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 20:00:43,892: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 20:00:43,893: INFO: common: created directory at: artifacts]
[2024-06-22 20:00:43,894: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-06-22 20:00:43,895: INFO: prepare_base_model: Initialized XGBClassifier with following parameters PrepareBaseModelConfig(params_n_estimators=500, params_learning_rate=0.1, params_random_state=42, params_subsample=0.5, params_n_jobs=-1, params_max_depth=3)]
[2024-06-22 20:00:43,895: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-06-22 20:00:43,895: INFO: main: *******************]
[2024-06-22 20:00:43,895: INFO: main: >>>>>> stage Train and save model started <<<<<<]
[2024-06-22 20:00:43,898: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 20:00:43,901: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 20:00:43,903: INFO: common: created directory at: artifacts]
[2024-06-22 20:00:43,904: INFO: common: created directory at: artifacts/training]
[2024-06-22 20:00:45,181: INFO: training: Model training and cross validation initiated.]
[2024-06-22 20:02:59,773: INFO: training: Cross Validation Scores: [0.99063215 0.98941648 0.9902746  0.98820164 0.98905971]]
[2024-06-22 20:02:59,773: INFO: training: Scores Mean:  0.9895169155985206]
[2024-06-22 20:02:59,775: INFO: training: Scores Standard Deviation: 0.0008679747406873597]
[2024-06-22 20:03:24,197: INFO: training: Model saved in path artifacts/training/model.pkl.]
[2024-06-22 20:03:24,198: INFO: main: >>>>>> stage Train and save model completed <<<<<<

x==========x]
[2024-06-22 20:03:24,202: INFO: main: *******************]
[2024-06-22 20:03:24,205: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-06-22 20:03:24,207: ERROR: main: Evaluation.__init__() missing 1 required positional argument: 'config']
Traceback (most recent call last):
  File "/home/nair.ro/mlops-model-dev/main.py", line 52, in <module>
    model_evalution.main(xgb)
  File "/home/nair.ro/mlops-model-dev/src/XGBClassifier/pipeline/stage_04_evaluation.py", line 16, in main
    evalu = Evaluation()
TypeError: Evaluation.__init__() missing 1 required positional argument: 'config'
[2024-06-22 20:03:58,453: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-06-22 20:03:58,457: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 20:03:58,460: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 20:03:58,461: INFO: common: created directory at: artifacts]
[2024-06-22 20:03:58,463: INFO: common: created directory at: artifacts/data_ingestion]
[2024-06-22 20:03:58,464: INFO: data_ingestion: File already exists of size: ~ 74490 KB]
[2024-06-22 20:03:58,467: INFO: data_ingestion:  File 'artifacts/data_ingestion/card_transdata.csv' is of type '.csv']
[2024-06-22 20:03:58,467: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-06-22 20:03:58,469: INFO: main: *******************]
[2024-06-22 20:03:58,470: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-06-22 20:03:58,475: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 20:03:58,478: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 20:03:58,479: INFO: common: created directory at: artifacts]
[2024-06-22 20:03:58,481: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-06-22 20:03:58,482: INFO: prepare_base_model: Initialized XGBClassifier with following parameters PrepareBaseModelConfig(params_n_estimators=500, params_learning_rate=0.1, params_random_state=42, params_subsample=0.5, params_n_jobs=-1, params_max_depth=3)]
[2024-06-22 20:03:58,484: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-06-22 20:03:58,485: INFO: main: *******************]
[2024-06-22 20:03:58,487: INFO: main: >>>>>> stage Train and save model started <<<<<<]
[2024-06-22 20:03:58,493: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 20:03:58,496: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 20:03:58,498: INFO: common: created directory at: artifacts]
[2024-06-22 20:03:58,498: INFO: common: created directory at: artifacts/training]
[2024-06-22 20:03:59,988: INFO: training: Model training and cross validation initiated.]
[2024-06-22 20:05:45,885: INFO: training: Cross Validation Scores: [0.99063215 0.98941648 0.9902746  0.98820164 0.98905971]]
[2024-06-22 20:05:45,886: INFO: training: Scores Mean:  0.9895169155985206]
[2024-06-22 20:05:45,888: INFO: training: Scores Standard Deviation: 0.0008679747406873597]
[2024-06-22 20:06:10,071: INFO: training: Model saved in path artifacts/training/model.pkl.]
[2024-06-22 20:06:10,072: INFO: main: >>>>>> stage Train and save model completed <<<<<<

x==========x]
[2024-06-22 20:06:10,074: INFO: main: *******************]
[2024-06-22 20:06:10,075: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-06-22 20:06:10,077: ERROR: main: Evaluation.__init__() missing 1 required positional argument: 'config']
Traceback (most recent call last):
  File "/home/nair.ro/mlops-model-dev/main.py", line 52, in <module>
    model_evalution.main(xgb)
  File "/home/nair.ro/mlops-model-dev/src/XGBClassifier/pipeline/stage_04_evaluation.py", line 16, in main
    evalu = Evaluation()
TypeError: Evaluation.__init__() missing 1 required positional argument: 'config'
[2024-06-22 20:09:42,278: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-06-22 20:09:42,282: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 20:09:42,284: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 20:09:42,285: INFO: common: created directory at: artifacts]
[2024-06-22 20:09:42,287: INFO: common: created directory at: artifacts/data_ingestion]
[2024-06-22 20:09:42,288: INFO: data_ingestion: File already exists of size: ~ 74490 KB]
[2024-06-22 20:09:42,295: INFO: data_ingestion:  File 'artifacts/data_ingestion/card_transdata.csv' is of type '.csv']
[2024-06-22 20:09:42,295: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-06-22 20:09:42,297: INFO: main: *******************]
[2024-06-22 20:09:42,300: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-06-22 20:09:42,308: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 20:09:42,311: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 20:09:42,312: INFO: common: created directory at: artifacts]
[2024-06-22 20:09:42,313: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-06-22 20:09:42,314: INFO: prepare_base_model: Initialized XGBClassifier with following parameters PrepareBaseModelConfig(params_n_estimators=500, params_learning_rate=0.1, params_random_state=42, params_subsample=0.5, params_n_jobs=-1, params_max_depth=3)]
[2024-06-22 20:09:42,316: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-06-22 20:09:42,317: INFO: main: *******************]
[2024-06-22 20:09:42,321: INFO: main: >>>>>> stage Train and save model started <<<<<<]
[2024-06-22 20:09:42,326: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 20:09:42,329: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 20:09:42,330: INFO: common: created directory at: artifacts]
[2024-06-22 20:09:42,331: INFO: common: created directory at: artifacts/training]
[2024-06-22 20:09:43,788: INFO: training: Model training and cross validation initiated.]
[2024-06-22 20:11:30,430: INFO: training: Cross Validation Scores: [0.99063215 0.98941648 0.9902746  0.98820164 0.98905971]]
[2024-06-22 20:11:30,431: INFO: training: Scores Mean:  0.9895169155985206]
[2024-06-22 20:11:30,433: INFO: training: Scores Standard Deviation: 0.0008679747406873597]
[2024-06-22 20:11:54,196: INFO: training: Model saved in path artifacts/training/model.pkl.]
[2024-06-22 20:11:54,197: INFO: main: >>>>>> stage Train and save model completed <<<<<<

x==========x]
[2024-06-22 20:11:54,200: INFO: main: *******************]
[2024-06-22 20:11:54,202: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-06-22 20:11:54,207: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 20:11:54,210: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 20:11:54,210: INFO: common: created directory at: artifacts]
[2024-06-22 20:11:54,212: ERROR: main: Evaluation.model_evaluation() missing 2 required positional arguments: 'X_test' and 'y_test']
Traceback (most recent call last):
  File "/home/nair.ro/mlops-model-dev/main.py", line 52, in <module>
    model_evalution.main(xgb)
  File "/home/nair.ro/mlops-model-dev/src/XGBClassifier/pipeline/stage_04_evaluation.py", line 19, in main
    evalu.model_evaluation(xgb)
TypeError: Evaluation.model_evaluation() missing 2 required positional arguments: 'X_test' and 'y_test'
[2024-06-22 20:13:02,666: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-06-22 20:13:02,670: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 20:13:02,674: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 20:13:02,674: INFO: common: created directory at: artifacts]
[2024-06-22 20:13:02,676: INFO: common: created directory at: artifacts/data_ingestion]
[2024-06-22 20:13:02,678: INFO: data_ingestion: File already exists of size: ~ 74490 KB]
[2024-06-22 20:13:02,682: INFO: data_ingestion:  File 'artifacts/data_ingestion/card_transdata.csv' is of type '.csv']
[2024-06-22 20:13:02,682: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-06-22 20:13:02,684: INFO: main: *******************]
[2024-06-22 20:13:02,686: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-06-22 20:13:02,689: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 20:13:02,691: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 20:13:02,692: INFO: common: created directory at: artifacts]
[2024-06-22 20:13:02,693: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-06-22 20:13:02,694: INFO: prepare_base_model: Initialized XGBClassifier with following parameters PrepareBaseModelConfig(params_n_estimators=500, params_learning_rate=0.1, params_random_state=42, params_subsample=0.5, params_n_jobs=-1, params_max_depth=3)]
[2024-06-22 20:13:02,696: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-06-22 20:13:02,697: INFO: main: *******************]
[2024-06-22 20:13:02,698: INFO: main: >>>>>> stage Train and save model started <<<<<<]
[2024-06-22 20:13:02,702: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 20:13:02,705: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 20:13:02,706: INFO: common: created directory at: artifacts]
[2024-06-22 20:13:02,707: INFO: common: created directory at: artifacts/training]
[2024-06-22 20:13:04,486: INFO: training: Model training and cross validation initiated.]
[2024-06-22 20:14:49,426: INFO: training: Cross Validation Scores: [0.99063215 0.98941648 0.9902746  0.98820164 0.98905971]]
[2024-06-22 20:14:49,427: INFO: training: Scores Mean:  0.9895169155985206]
[2024-06-22 20:14:49,429: INFO: training: Scores Standard Deviation: 0.0008679747406873597]
[2024-06-22 20:15:13,267: INFO: training: Model saved in path artifacts/training/model.pkl.]
[2024-06-22 20:15:13,268: INFO: main: >>>>>> stage Train and save model completed <<<<<<

x==========x]
[2024-06-22 20:15:13,270: INFO: main: *******************]
[2024-06-22 20:15:13,271: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-06-22 20:15:13,277: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 20:15:13,279: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 20:15:13,281: INFO: common: created directory at: artifacts]
[2024-06-22 20:15:13,282: ERROR: main: name 'X_test' is not defined]
Traceback (most recent call last):
  File "/home/nair.ro/mlops-model-dev/main.py", line 52, in <module>
    model_evalution.main(xgb)
  File "/home/nair.ro/mlops-model-dev/src/XGBClassifier/pipeline/stage_04_evaluation.py", line 19, in main
    evalu.model_evaluation(xgb)
  File "/home/nair.ro/mlops-model-dev/src/XGBClassifier/components/evaluation.py", line 53, in model_evaluation
    y_proba_test = model.predict_proba(X_test)
NameError: name 'X_test' is not defined
[2024-06-22 20:15:19,009: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-06-22 20:15:19,012: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 20:15:19,016: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 20:15:19,017: INFO: common: created directory at: artifacts]
[2024-06-22 20:15:19,018: INFO: common: created directory at: artifacts/data_ingestion]
[2024-06-22 20:15:19,020: INFO: data_ingestion: File already exists of size: ~ 74490 KB]
[2024-06-22 20:15:19,022: INFO: data_ingestion:  File 'artifacts/data_ingestion/card_transdata.csv' is of type '.csv']
[2024-06-22 20:15:19,022: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-06-22 20:15:19,024: INFO: main: *******************]
[2024-06-22 20:15:19,025: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-06-22 20:15:19,032: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 20:15:19,034: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 20:15:19,035: INFO: common: created directory at: artifacts]
[2024-06-22 20:15:19,036: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-06-22 20:15:19,037: INFO: prepare_base_model: Initialized XGBClassifier with following parameters PrepareBaseModelConfig(params_n_estimators=500, params_learning_rate=0.1, params_random_state=42, params_subsample=0.5, params_n_jobs=-1, params_max_depth=3)]
[2024-06-22 20:15:19,038: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-06-22 20:15:19,039: INFO: main: *******************]
[2024-06-22 20:15:19,040: INFO: main: >>>>>> stage Train and save model started <<<<<<]
[2024-06-22 20:15:19,045: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 20:15:19,047: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 20:15:19,050: INFO: common: created directory at: artifacts]
[2024-06-22 20:15:19,067: INFO: common: created directory at: artifacts/training]
[2024-06-22 20:16:07,026: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-06-22 20:16:07,029: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 20:16:07,031: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 20:16:07,032: INFO: common: created directory at: artifacts]
[2024-06-22 20:16:07,034: INFO: common: created directory at: artifacts/data_ingestion]
[2024-06-22 20:16:07,035: INFO: data_ingestion: File already exists of size: ~ 74490 KB]
[2024-06-22 20:16:07,038: INFO: data_ingestion:  File 'artifacts/data_ingestion/card_transdata.csv' is of type '.csv']
[2024-06-22 20:16:07,039: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-06-22 20:16:07,040: INFO: main: *******************]
[2024-06-22 20:16:07,042: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-06-22 20:16:07,045: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 20:16:07,048: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 20:16:07,049: INFO: common: created directory at: artifacts]
[2024-06-22 20:16:07,051: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-06-22 20:16:07,053: INFO: prepare_base_model: Initialized XGBClassifier with following parameters PrepareBaseModelConfig(params_n_estimators=500, params_learning_rate=0.1, params_random_state=42, params_subsample=0.5, params_n_jobs=-1, params_max_depth=3)]
[2024-06-22 20:16:07,054: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-06-22 20:16:07,056: INFO: main: *******************]
[2024-06-22 20:16:07,057: INFO: main: >>>>>> stage Train and save model started <<<<<<]
[2024-06-22 20:16:07,061: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 20:16:07,063: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 20:16:07,073: INFO: common: created directory at: artifacts]
[2024-06-22 20:16:07,075: INFO: common: created directory at: artifacts/training]
[2024-06-22 20:16:08,358: INFO: training: Model training and cross validation initiated.]
[2024-06-22 20:17:54,174: INFO: training: Cross Validation Scores: [0.99063215 0.98941648 0.9902746  0.98820164 0.98905971]]
[2024-06-22 20:17:54,175: INFO: training: Scores Mean:  0.9895169155985206]
[2024-06-22 20:17:54,175: INFO: training: Scores Standard Deviation: 0.0008679747406873597]
[2024-06-22 20:18:17,812: INFO: training: Model saved in path artifacts/training/model.pkl.]
[2024-06-22 20:18:17,813: INFO: main: >>>>>> stage Train and save model completed <<<<<<

x==========x]
[2024-06-22 20:18:17,814: INFO: main: *******************]
[2024-06-22 20:18:17,815: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-06-22 20:18:17,821: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 20:18:17,823: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 20:18:17,824: INFO: common: created directory at: artifacts]
[2024-06-22 20:18:17,827: ERROR: main: name 'pd' is not defined]
Traceback (most recent call last):
  File "/home/nair.ro/mlops-model-dev/main.py", line 52, in <module>
    model_evalution.main(xgb)
  File "/home/nair.ro/mlops-model-dev/src/XGBClassifier/pipeline/stage_04_evaluation.py", line 19, in main
    evalu.model_evaluation(xgb)
  File "/home/nair.ro/mlops-model-dev/src/XGBClassifier/components/evaluation.py", line 53, in model_evaluation
    X_train , X_test ,y_train , y_test  = self.train_valid_generator()
  File "/home/nair.ro/mlops-model-dev/src/XGBClassifier/components/evaluation.py", line 15, in train_valid_generator
    df = pd.read_csv(self.config.training_data,encoding='utf-8')
NameError: name 'pd' is not defined
[2024-06-22 20:21:44,266: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-06-22 20:21:44,270: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 20:21:44,274: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 20:21:44,276: INFO: common: created directory at: artifacts]
[2024-06-22 20:21:44,277: INFO: common: created directory at: artifacts/data_ingestion]
[2024-06-22 20:21:44,279: INFO: data_ingestion: File already exists of size: ~ 74490 KB]
[2024-06-22 20:21:44,281: INFO: data_ingestion:  File 'artifacts/data_ingestion/card_transdata.csv' is of type '.csv']
[2024-06-22 20:21:44,282: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-06-22 20:21:44,283: INFO: main: *******************]
[2024-06-22 20:21:44,285: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-06-22 20:21:44,289: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 20:21:44,292: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 20:21:44,292: INFO: common: created directory at: artifacts]
[2024-06-22 20:21:44,294: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-06-22 20:21:44,295: INFO: prepare_base_model: Initialized XGBClassifier with following parameters PrepareBaseModelConfig(params_n_estimators=500, params_learning_rate=0.1, params_random_state=42, params_subsample=0.5, params_n_jobs=-1, params_max_depth=3)]
[2024-06-22 20:21:44,298: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-06-22 20:21:44,299: INFO: main: *******************]
[2024-06-22 20:21:44,301: INFO: main: >>>>>> stage Train and save model started <<<<<<]
[2024-06-22 20:21:44,305: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 20:21:44,308: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 20:21:44,308: INFO: common: created directory at: artifacts]
[2024-06-22 20:21:44,311: INFO: common: created directory at: artifacts/training]
[2024-06-22 20:21:45,541: INFO: training: Model training and cross validation initiated.]
[2024-06-22 20:27:47,033: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-06-22 20:27:47,042: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 20:27:47,056: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 20:27:47,058: INFO: common: created directory at: artifacts]
[2024-06-22 20:27:47,062: INFO: common: created directory at: artifacts/data_ingestion]
[2024-06-22 20:27:47,067: INFO: data_ingestion: File already exists of size: ~ 74490 KB]
[2024-06-22 20:27:47,086: INFO: data_ingestion:  File 'artifacts/data_ingestion/card_transdata.csv' is of type '.csv']
[2024-06-22 20:27:47,087: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-06-22 20:27:47,093: INFO: main: *******************]
[2024-06-22 20:27:47,095: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-06-22 20:27:47,106: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 20:27:47,110: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 20:27:47,112: INFO: common: created directory at: artifacts]
[2024-06-22 20:27:47,115: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-06-22 20:27:47,117: INFO: prepare_base_model: Initialized XGBClassifier with following parameters PrepareBaseModelConfig(params_n_estimators=500, params_learning_rate=0.1, params_random_state=42, params_subsample=0.5, params_n_jobs=-1, params_max_depth=3)]
[2024-06-22 20:27:47,119: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-06-22 20:27:47,123: INFO: main: *******************]
[2024-06-22 20:27:47,136: INFO: main: >>>>>> stage Train and save model started <<<<<<]
[2024-06-22 20:27:47,145: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 20:27:47,149: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 20:27:47,152: INFO: common: created directory at: artifacts]
[2024-06-22 20:27:47,154: INFO: common: created directory at: artifacts/training]
[2024-06-22 20:27:48,790: INFO: training: Model training and cross validation initiated.]
[2024-06-22 20:29:41,168: INFO: training: Cross Validation Scores: [0.99063215 0.98941648 0.9902746  0.98820164 0.98905971]]
[2024-06-22 20:29:41,169: INFO: training: Scores Mean:  0.9895169155985206]
[2024-06-22 20:29:41,171: INFO: training: Scores Standard Deviation: 0.0008679747406873597]
[2024-06-22 20:30:08,959: INFO: training: Model saved in path artifacts/training/model.pkl.]
[2024-06-22 20:30:08,961: INFO: main: >>>>>> stage Train and save model completed <<<<<<

x==========x]
[2024-06-22 20:30:08,963: INFO: main: *******************]
[2024-06-22 20:30:08,965: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-06-22 20:30:08,975: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 20:30:08,983: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 20:30:09,019: INFO: common: created directory at: artifacts]
[2024-06-22 20:30:09,028: ERROR: main: 'EvaluationConfig' object has no attribute 'training_data']
Traceback (most recent call last):
  File "/home/nair.ro/mlops-model-dev/main.py", line 52, in <module>
    model_evalution.main(xgb)
  File "/home/nair.ro/mlops-model-dev/src/XGBClassifier/pipeline/stage_04_evaluation.py", line 19, in main
    evalu.model_evaluation(xgb)
  File "/home/nair.ro/mlops-model-dev/src/XGBClassifier/components/evaluation.py", line 53, in model_evaluation
    X_train , X_test ,y_train , y_test  = self.train_valid_generator()
  File "/home/nair.ro/mlops-model-dev/src/XGBClassifier/components/evaluation.py", line 15, in train_valid_generator
    df = pd.read_csv(self.config.training_data,encoding='utf-8')
AttributeError: 'EvaluationConfig' object has no attribute 'training_data'
[2024-06-22 20:31:54,659: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-06-22 20:31:54,663: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 20:31:54,667: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 20:31:54,668: INFO: common: created directory at: artifacts]
[2024-06-22 20:31:54,670: INFO: common: created directory at: artifacts/data_ingestion]
[2024-06-22 20:31:54,671: INFO: data_ingestion: File already exists of size: ~ 74490 KB]
[2024-06-22 20:31:54,673: INFO: data_ingestion:  File 'artifacts/data_ingestion/card_transdata.csv' is of type '.csv']
[2024-06-22 20:31:54,674: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-06-22 20:31:54,676: INFO: main: *******************]
[2024-06-22 20:31:54,677: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-06-22 20:31:54,682: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 20:31:54,684: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 20:31:54,685: INFO: common: created directory at: artifacts]
[2024-06-22 20:31:54,686: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-06-22 20:31:54,687: INFO: prepare_base_model: Initialized XGBClassifier with following parameters PrepareBaseModelConfig(params_n_estimators=500, params_learning_rate=0.1, params_random_state=42, params_subsample=0.5, params_n_jobs=-1, params_max_depth=3)]
[2024-06-22 20:31:54,689: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-06-22 20:31:54,692: INFO: main: *******************]
[2024-06-22 20:31:54,693: INFO: main: >>>>>> stage Train and save model started <<<<<<]
[2024-06-22 20:31:54,699: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 20:31:54,701: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 20:31:54,702: INFO: common: created directory at: artifacts]
[2024-06-22 20:31:54,703: INFO: common: created directory at: artifacts/training]
[2024-06-22 20:31:56,074: INFO: training: Model training and cross validation initiated.]
[2024-06-22 20:34:13,391: INFO: training: Cross Validation Scores: [0.99063215 0.98941648 0.9902746  0.98820164 0.98905971]]
[2024-06-22 20:34:13,392: INFO: training: Scores Mean:  0.9895169155985206]
[2024-06-22 20:34:13,395: INFO: training: Scores Standard Deviation: 0.0008679747406873597]
[2024-06-22 20:34:40,041: INFO: training: Model saved in path artifacts/training/model.pkl.]
[2024-06-22 20:34:40,042: INFO: main: >>>>>> stage Train and save model completed <<<<<<

x==========x]
[2024-06-22 20:34:40,044: INFO: main: *******************]
[2024-06-22 20:34:40,046: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-06-22 20:34:40,052: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 20:34:40,054: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 20:34:40,055: INFO: common: created directory at: artifacts]
[2024-06-22 20:34:40,859: ERROR: main: name 'train_test_split' is not defined]
Traceback (most recent call last):
  File "/home/nair.ro/mlops-model-dev/main.py", line 52, in <module>
    model_evalution.main(xgb)
  File "/home/nair.ro/mlops-model-dev/src/XGBClassifier/pipeline/stage_04_evaluation.py", line 19, in main
    evalu.model_evaluation(xgb)
  File "/home/nair.ro/mlops-model-dev/src/XGBClassifier/components/evaluation.py", line 53, in model_evaluation
    X_train , X_test ,y_train , y_test  = self.train_valid_generator()
  File "/home/nair.ro/mlops-model-dev/src/XGBClassifier/components/evaluation.py", line 21, in train_valid_generator
    X_train , X_test ,y_train , y_test = train_test_split(X,y,test_size = self.config.test_size ,random_state =self.config.random_state  ,stratify=y)
NameError: name 'train_test_split' is not defined
[2024-06-22 20:35:38,892: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-06-22 20:35:38,897: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 20:35:38,903: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 20:35:38,904: INFO: common: created directory at: artifacts]
[2024-06-22 20:35:38,907: INFO: common: created directory at: artifacts/data_ingestion]
[2024-06-22 20:35:38,909: INFO: data_ingestion: File already exists of size: ~ 74490 KB]
[2024-06-22 20:35:38,912: INFO: data_ingestion:  File 'artifacts/data_ingestion/card_transdata.csv' is of type '.csv']
[2024-06-22 20:35:38,913: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-06-22 20:35:38,916: INFO: main: *******************]
[2024-06-22 20:35:38,918: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-06-22 20:35:38,923: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 20:35:38,926: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 20:35:38,928: INFO: common: created directory at: artifacts]
[2024-06-22 20:35:38,930: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-06-22 20:35:38,931: INFO: prepare_base_model: Initialized XGBClassifier with following parameters PrepareBaseModelConfig(params_n_estimators=500, params_learning_rate=0.1, params_random_state=42, params_subsample=0.5, params_n_jobs=-1, params_max_depth=3)]
[2024-06-22 20:35:38,935: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-06-22 20:35:38,936: INFO: main: *******************]
[2024-06-22 20:35:38,938: INFO: main: >>>>>> stage Train and save model started <<<<<<]
[2024-06-22 20:35:38,945: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 20:35:38,947: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 20:35:38,950: INFO: common: created directory at: artifacts]
[2024-06-22 20:35:38,951: INFO: common: created directory at: artifacts/training]
[2024-06-22 20:35:40,445: INFO: training: Model training and cross validation initiated.]
[2024-06-22 20:37:25,090: INFO: training: Cross Validation Scores: [0.99063215 0.98941648 0.9902746  0.98820164 0.98905971]]
[2024-06-22 20:37:25,091: INFO: training: Scores Mean:  0.9895169155985206]
[2024-06-22 20:37:25,095: INFO: training: Scores Standard Deviation: 0.0008679747406873597]
[2024-06-22 20:37:48,727: INFO: training: Model saved in path artifacts/training/model.pkl.]
[2024-06-22 20:37:48,728: INFO: main: >>>>>> stage Train and save model completed <<<<<<

x==========x]
[2024-06-22 20:37:48,730: INFO: main: *******************]
[2024-06-22 20:37:48,731: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-06-22 20:37:48,737: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 20:37:48,739: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 20:37:48,741: INFO: common: created directory at: artifacts]
[2024-06-22 20:37:49,525: ERROR: main: 'EvaluationConfig' object has no attribute 'test_size']
Traceback (most recent call last):
  File "/home/nair.ro/mlops-model-dev/main.py", line 52, in <module>
    model_evalution.main(xgb)
  File "/home/nair.ro/mlops-model-dev/src/XGBClassifier/pipeline/stage_04_evaluation.py", line 19, in main
    evalu.model_evaluation(xgb)
  File "/home/nair.ro/mlops-model-dev/src/XGBClassifier/components/evaluation.py", line 55, in model_evaluation
    X_train , X_test ,y_train , y_test  = self.train_valid_generator()
  File "/home/nair.ro/mlops-model-dev/src/XGBClassifier/components/evaluation.py", line 23, in train_valid_generator
    X_train , X_test ,y_train , y_test = train_test_split(X,y,test_size = self.config.test_size ,random_state =self.config.random_state  ,stratify=y)
AttributeError: 'EvaluationConfig' object has no attribute 'test_size'
[2024-06-22 20:39:12,370: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-06-22 20:39:12,374: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 20:39:12,378: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 20:39:12,379: INFO: common: created directory at: artifacts]
[2024-06-22 20:39:12,380: INFO: common: created directory at: artifacts/data_ingestion]
[2024-06-22 20:39:12,381: INFO: data_ingestion: File already exists of size: ~ 74490 KB]
[2024-06-22 20:39:12,385: INFO: data_ingestion:  File 'artifacts/data_ingestion/card_transdata.csv' is of type '.csv']
[2024-06-22 20:39:12,385: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-06-22 20:39:12,387: INFO: main: *******************]
[2024-06-22 20:39:12,388: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-06-22 20:39:12,393: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 20:39:12,396: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 20:39:12,398: INFO: common: created directory at: artifacts]
[2024-06-22 20:39:12,399: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-06-22 20:39:12,400: INFO: prepare_base_model: Initialized XGBClassifier with following parameters PrepareBaseModelConfig(params_n_estimators=500, params_learning_rate=0.1, params_random_state=42, params_subsample=0.5, params_n_jobs=-1, params_max_depth=3)]
[2024-06-22 20:39:12,402: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-06-22 20:39:12,404: INFO: main: *******************]
[2024-06-22 20:39:12,419: INFO: main: >>>>>> stage Train and save model started <<<<<<]
[2024-06-22 20:39:12,423: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 20:39:12,426: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 20:39:12,427: INFO: common: created directory at: artifacts]
[2024-06-22 20:39:12,427: INFO: common: created directory at: artifacts/training]
[2024-06-22 20:39:13,894: INFO: training: Model training and cross validation initiated.]
[2024-06-22 20:41:02,428: INFO: training: Cross Validation Scores: [0.99063215 0.98941648 0.9902746  0.98820164 0.98905971]]
[2024-06-22 20:41:02,429: INFO: training: Scores Mean:  0.9895169155985206]
[2024-06-22 20:41:02,433: INFO: training: Scores Standard Deviation: 0.0008679747406873597]
[2024-06-22 20:41:30,334: INFO: training: Model saved in path artifacts/training/model.pkl.]
[2024-06-22 20:41:30,335: INFO: main: >>>>>> stage Train and save model completed <<<<<<

x==========x]
[2024-06-22 20:41:30,336: INFO: main: *******************]
[2024-06-22 20:41:30,338: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-06-22 20:41:30,344: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 20:41:30,347: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 20:41:30,348: INFO: common: created directory at: artifacts]
[2024-06-22 20:41:36,498: INFO: evaluation:               precision    recall  f1-score   support

         0.0       1.00      1.00      1.00    182519
         1.0       0.99      0.99      0.99     17481

    accuracy                           1.00    200000
   macro avg       0.99      0.99      0.99    200000
weighted avg       1.00      1.00      1.00    200000
]
[2024-06-22 20:41:36,793: ERROR: main: save_figure_with_timestamp() missing 1 required positional argument: 'fig']
Traceback (most recent call last):
  File "/home/nair.ro/mlops-model-dev/main.py", line 52, in <module>
    model_evalution.main(xgb)
  File "/home/nair.ro/mlops-model-dev/src/XGBClassifier/pipeline/stage_04_evaluation.py", line 19, in main
    evalu.model_evaluation(xgb)
  File "/home/nair.ro/mlops-model-dev/src/XGBClassifier/components/evaluation.py", line 68, in model_evaluation
    save_figure_with_timestamp(prefix="confusion_matrix")
TypeError: save_figure_with_timestamp() missing 1 required positional argument: 'fig'
[2024-06-22 20:45:53,863: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-06-22 20:45:53,867: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 20:45:53,871: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 20:45:53,872: INFO: common: created directory at: artifacts]
[2024-06-22 20:45:53,877: INFO: common: created directory at: artifacts/data_ingestion]
[2024-06-22 20:45:53,880: INFO: data_ingestion: File already exists of size: ~ 74490 KB]
[2024-06-22 20:45:53,882: INFO: data_ingestion:  File 'artifacts/data_ingestion/card_transdata.csv' is of type '.csv']
[2024-06-22 20:45:53,882: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-06-22 20:45:53,884: INFO: main: *******************]
[2024-06-22 20:45:53,885: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-06-22 20:45:53,890: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 20:45:53,892: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 20:45:53,893: INFO: common: created directory at: artifacts]
[2024-06-22 20:45:53,895: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-06-22 20:45:53,896: INFO: prepare_base_model: Initialized XGBClassifier with following parameters PrepareBaseModelConfig(params_n_estimators=500, params_learning_rate=0.1, params_random_state=42, params_subsample=0.5, params_n_jobs=-1, params_max_depth=3)]
[2024-06-22 20:45:53,898: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-06-22 20:45:53,900: INFO: main: *******************]
[2024-06-22 20:45:53,902: INFO: main: >>>>>> stage Train and save model started <<<<<<]
[2024-06-22 20:45:53,908: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 20:45:53,911: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 20:45:53,912: INFO: common: created directory at: artifacts]
[2024-06-22 20:45:53,913: INFO: common: created directory at: artifacts/training]
[2024-06-22 20:45:55,288: INFO: training: Model training and cross validation initiated.]
[2024-06-22 20:47:42,730: INFO: training: Cross Validation Scores: [0.99063215 0.98941648 0.9902746  0.98820164 0.98905971]]
[2024-06-22 20:47:42,730: INFO: training: Scores Mean:  0.9895169155985206]
[2024-06-22 20:47:42,744: INFO: training: Scores Standard Deviation: 0.0008679747406873597]
[2024-06-22 20:48:07,108: INFO: training: Model saved in path artifacts/training/model.pkl.]
[2024-06-22 20:48:07,110: INFO: main: >>>>>> stage Train and save model completed <<<<<<

x==========x]
[2024-06-22 20:48:07,112: INFO: main: *******************]
[2024-06-22 20:48:07,113: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-06-22 20:48:07,142: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 20:48:07,146: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 20:48:07,150: INFO: common: created directory at: artifacts]
[2024-06-22 20:48:07,150: ERROR: main: Evaluation.model_evaluation() missing 1 required positional argument: 'y_test']
Traceback (most recent call last):
  File "/home/nair.ro/mlops-model-dev/main.py", line 52, in <module>
    model_evalution.main(xgb)
  File "/home/nair.ro/mlops-model-dev/src/XGBClassifier/pipeline/stage_04_evaluation.py", line 19, in main
    evalu.model_evaluation(xgb)
TypeError: Evaluation.model_evaluation() missing 1 required positional argument: 'y_test'
[2024-06-22 20:48:47,530: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-06-22 20:48:47,534: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 20:48:47,538: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 20:48:47,539: INFO: common: created directory at: artifacts]
[2024-06-22 20:48:47,540: INFO: common: created directory at: artifacts/data_ingestion]
[2024-06-22 20:48:47,542: INFO: data_ingestion: File already exists of size: ~ 74490 KB]
[2024-06-22 20:48:47,543: INFO: data_ingestion:  File 'artifacts/data_ingestion/card_transdata.csv' is of type '.csv']
[2024-06-22 20:48:47,544: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-06-22 20:48:47,545: INFO: main: *******************]
[2024-06-22 20:48:47,546: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-06-22 20:48:47,550: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 20:48:47,554: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 20:48:47,555: INFO: common: created directory at: artifacts]
[2024-06-22 20:48:47,558: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-06-22 20:48:47,559: INFO: prepare_base_model: Initialized XGBClassifier with following parameters PrepareBaseModelConfig(params_n_estimators=500, params_learning_rate=0.1, params_random_state=42, params_subsample=0.5, params_n_jobs=-1, params_max_depth=3)]
[2024-06-22 20:48:47,563: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-06-22 20:48:47,567: INFO: main: *******************]
[2024-06-22 20:48:47,568: INFO: main: >>>>>> stage Train and save model started <<<<<<]
[2024-06-22 20:48:47,573: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 20:48:47,575: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 20:48:47,576: INFO: common: created directory at: artifacts]
[2024-06-22 20:48:47,578: INFO: common: created directory at: artifacts/training]
[2024-06-22 20:48:49,139: INFO: training: Model training and cross validation initiated.]
[2024-06-22 20:50:34,570: INFO: training: Cross Validation Scores: [0.99063215 0.98941648 0.9902746  0.98820164 0.98905971]]
[2024-06-22 20:50:34,572: INFO: training: Scores Mean:  0.9895169155985206]
[2024-06-22 20:50:34,575: INFO: training: Scores Standard Deviation: 0.0008679747406873597]
[2024-06-22 20:50:58,283: INFO: training: Model saved in path artifacts/training/model.pkl.]
[2024-06-22 20:50:58,284: INFO: main: >>>>>> stage Train and save model completed <<<<<<

x==========x]
[2024-06-22 20:50:58,286: INFO: main: *******************]
[2024-06-22 20:50:58,287: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-06-22 20:50:58,293: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 20:50:58,295: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 20:50:58,296: INFO: common: created directory at: artifacts]
[2024-06-22 20:50:58,297: ERROR: main: name 'X_test' is not defined]
Traceback (most recent call last):
  File "/home/nair.ro/mlops-model-dev/main.py", line 52, in <module>
    model_evalution.main(xgb)
  File "/home/nair.ro/mlops-model-dev/src/XGBClassifier/pipeline/stage_04_evaluation.py", line 19, in main
    evalu.model_evaluation(xgb)
  File "/home/nair.ro/mlops-model-dev/src/XGBClassifier/components/evaluation.py", line 56, in model_evaluation
    y_proba_test = model.predict_proba(X_test)
NameError: name 'X_test' is not defined
[2024-06-22 20:52:43,687: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-06-22 20:52:43,691: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 20:52:43,694: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 20:52:43,695: INFO: common: created directory at: artifacts]
[2024-06-22 20:52:43,696: INFO: common: created directory at: artifacts/data_ingestion]
[2024-06-22 20:52:43,697: INFO: data_ingestion: File already exists of size: ~ 74490 KB]
[2024-06-22 20:52:43,699: INFO: data_ingestion:  File 'artifacts/data_ingestion/card_transdata.csv' is of type '.csv']
[2024-06-22 20:52:43,700: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-06-22 20:52:43,701: INFO: main: *******************]
[2024-06-22 20:52:43,703: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-06-22 20:52:43,707: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 20:52:43,709: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 20:52:43,710: INFO: common: created directory at: artifacts]
[2024-06-22 20:52:43,711: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-06-22 20:52:43,712: INFO: prepare_base_model: Initialized XGBClassifier with following parameters PrepareBaseModelConfig(params_n_estimators=500, params_learning_rate=0.1, params_random_state=42, params_subsample=0.5, params_n_jobs=-1, params_max_depth=3)]
[2024-06-22 20:52:43,714: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-06-22 20:52:43,715: INFO: main: *******************]
[2024-06-22 20:52:43,716: INFO: main: >>>>>> stage Train and save model started <<<<<<]
[2024-06-22 20:52:43,720: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 20:52:43,722: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 20:52:43,724: INFO: common: created directory at: artifacts]
[2024-06-22 20:52:43,724: INFO: common: created directory at: artifacts/training]
[2024-06-22 20:52:45,063: INFO: training: Model training and cross validation initiated.]
[2024-06-22 20:54:30,168: INFO: training: Cross Validation Scores: [0.99063215 0.98941648 0.9902746  0.98820164 0.98905971]]
[2024-06-22 20:54:30,169: INFO: training: Scores Mean:  0.9895169155985206]
[2024-06-22 20:54:30,173: INFO: training: Scores Standard Deviation: 0.0008679747406873597]
[2024-06-22 20:54:53,926: INFO: training: Model saved in path artifacts/training/model.pkl.]
[2024-06-22 20:54:53,926: INFO: main: >>>>>> stage Train and save model completed <<<<<<

x==========x]
[2024-06-22 20:54:53,928: INFO: main: *******************]
[2024-06-22 20:54:53,930: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-06-22 20:54:53,935: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 20:54:53,938: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 20:54:53,939: INFO: common: created directory at: artifacts]
[2024-06-22 20:54:58,388: ERROR: main: name 'px' is not defined]
Traceback (most recent call last):
  File "/home/nair.ro/mlops-model-dev/main.py", line 52, in <module>
    model_evalution.main(xgb)
  File "/home/nair.ro/mlops-model-dev/src/XGBClassifier/pipeline/stage_04_evaluation.py", line 19, in main
    evalu.model_evaluation(xgb)
  File "/home/nair.ro/mlops-model-dev/src/XGBClassifier/components/evaluation.py", line 65, in model_evaluation
    fig = px.imshow(cm_df, text_auto=True, color_continuous_scale=color,
NameError: name 'px' is not defined
[2024-06-22 20:55:39,748: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-06-22 20:55:39,753: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 20:55:39,771: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 20:55:39,772: INFO: common: created directory at: artifacts]
[2024-06-22 20:55:39,774: INFO: common: created directory at: artifacts/data_ingestion]
[2024-06-22 20:55:39,775: INFO: data_ingestion: File already exists of size: ~ 74490 KB]
[2024-06-22 20:55:39,777: INFO: data_ingestion:  File 'artifacts/data_ingestion/card_transdata.csv' is of type '.csv']
[2024-06-22 20:55:39,778: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-06-22 20:55:39,785: INFO: main: *******************]
[2024-06-22 20:55:39,792: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-06-22 20:55:39,803: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 20:55:39,814: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 20:55:39,831: INFO: common: created directory at: artifacts]
[2024-06-22 20:55:39,843: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-06-22 20:55:39,845: INFO: prepare_base_model: Initialized XGBClassifier with following parameters PrepareBaseModelConfig(params_n_estimators=500, params_learning_rate=0.1, params_random_state=42, params_subsample=0.5, params_n_jobs=-1, params_max_depth=3)]
[2024-06-22 20:55:39,847: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-06-22 20:55:39,849: INFO: main: *******************]
[2024-06-22 20:55:39,850: INFO: main: >>>>>> stage Train and save model started <<<<<<]
[2024-06-22 20:55:39,857: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 20:55:39,874: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 20:55:39,876: INFO: common: created directory at: artifacts]
[2024-06-22 20:55:39,882: INFO: common: created directory at: artifacts/training]
[2024-06-22 20:55:41,287: INFO: training: Model training and cross validation initiated.]
[2024-06-22 20:57:27,141: INFO: training: Cross Validation Scores: [0.99063215 0.98941648 0.9902746  0.98820164 0.98905971]]
[2024-06-22 20:57:27,142: INFO: training: Scores Mean:  0.9895169155985206]
[2024-06-22 20:57:27,146: INFO: training: Scores Standard Deviation: 0.0008679747406873597]
[2024-06-22 20:57:50,942: INFO: training: Model saved in path artifacts/training/model.pkl.]
[2024-06-22 20:57:50,943: INFO: main: >>>>>> stage Train and save model completed <<<<<<

x==========x]
[2024-06-22 20:57:50,948: INFO: main: *******************]
[2024-06-22 20:57:50,950: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-06-22 20:57:50,959: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 20:57:50,968: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 20:57:50,975: INFO: common: created directory at: artifacts]
[2024-06-22 20:58:02,171: ERROR: main: 
Image export using the "kaleido" engine requires the kaleido package,
which can be installed using pip:
    $ pip install -U kaleido
]
Traceback (most recent call last):
  File "/home/nair.ro/mlops-model-dev/main.py", line 52, in <module>
    model_evalution.main(xgb)
  File "/home/nair.ro/mlops-model-dev/src/XGBClassifier/pipeline/stage_04_evaluation.py", line 19, in main
    evalu.model_evaluation(xgb)
  File "/home/nair.ro/mlops-model-dev/src/XGBClassifier/components/evaluation.py", line 71, in model_evaluation
    save_figure_with_timestamp(fig, prefix="confusion_matrix")
  File "/home/nair.ro/mlops-model-dev/src/XGBClassifier/utils/common.py", line 140, in save_figure_with_timestamp
    write_image(fig, filename)
  File "/home/nair.ro/miniforge3/lib/python3.10/site-packages/plotly/io/_kaleido.py", line 266, in write_image
    img_data = to_image(
  File "/home/nair.ro/miniforge3/lib/python3.10/site-packages/plotly/io/_kaleido.py", line 132, in to_image
    raise ValueError(
ValueError: 
Image export using the "kaleido" engine requires the kaleido package,
which can be installed using pip:
    $ pip install -U kaleido

[2024-06-22 21:02:16,873: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-06-22 21:02:16,880: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 21:02:16,888: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 21:02:16,890: INFO: common: created directory at: artifacts]
[2024-06-22 21:02:16,899: INFO: common: created directory at: artifacts/data_ingestion]
[2024-06-22 21:02:16,904: INFO: data_ingestion: File already exists of size: ~ 74490 KB]
[2024-06-22 21:02:16,910: INFO: data_ingestion:  File 'artifacts/data_ingestion/card_transdata.csv' is of type '.csv']
[2024-06-22 21:02:16,911: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-06-22 21:02:16,914: INFO: main: *******************]
[2024-06-22 21:02:16,921: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-06-22 21:02:16,936: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 21:02:16,949: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 21:02:16,953: INFO: common: created directory at: artifacts]
[2024-06-22 21:02:16,960: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-06-22 21:02:16,961: INFO: prepare_base_model: Initialized XGBClassifier with following parameters PrepareBaseModelConfig(params_n_estimators=500, params_learning_rate=0.1, params_random_state=42, params_subsample=0.5, params_n_jobs=-1, params_max_depth=3)]
[2024-06-22 21:02:16,963: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-06-22 21:02:16,966: INFO: main: *******************]
[2024-06-22 21:02:16,969: INFO: main: >>>>>> stage Train and save model started <<<<<<]
[2024-06-22 21:02:16,976: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 21:02:16,986: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 21:02:16,988: INFO: common: created directory at: artifacts]
[2024-06-22 21:02:16,998: INFO: common: created directory at: artifacts/training]
[2024-06-22 21:02:18,621: INFO: training: Model training and cross validation initiated.]
[2024-06-22 21:04:12,661: INFO: training: Cross Validation Scores: [0.99063215 0.98941648 0.9902746  0.98820164 0.98905971]]
[2024-06-22 21:04:12,662: INFO: training: Scores Mean:  0.9895169155985206]
[2024-06-22 21:04:12,662: INFO: training: Scores Standard Deviation: 0.0008679747406873597]
[2024-06-22 21:04:36,685: INFO: training: Model saved in path artifacts/training/model.pkl.]
[2024-06-22 21:04:36,688: INFO: main: >>>>>> stage Train and save model completed <<<<<<

x==========x]
[2024-06-22 21:04:36,695: INFO: main: *******************]
[2024-06-22 21:04:36,707: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-06-22 21:04:36,715: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 21:04:36,724: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 21:04:36,727: INFO: common: created directory at: artifacts]
[2024-06-22 21:04:46,396: INFO: common: Figure saved as: confusion_matrix_20240622_210444.png]
[2024-06-22 21:04:46,403: ERROR: main: Evaluation.precision_recall_trade_off() missing 2 required positional arguments: 'X_test' and 'y_test']
Traceback (most recent call last):
  File "/home/nair.ro/mlops-model-dev/main.py", line 52, in <module>
    model_evalution.main(xgb)
  File "/home/nair.ro/mlops-model-dev/src/XGBClassifier/pipeline/stage_04_evaluation.py", line 21, in main
    evalu.precision_recall_trade_off(xgb)
TypeError: Evaluation.precision_recall_trade_off() missing 2 required positional arguments: 'X_test' and 'y_test'
[2024-06-22 21:05:22,507: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-06-22 21:05:22,511: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 21:05:22,514: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 21:05:22,515: INFO: common: created directory at: artifacts]
[2024-06-22 21:05:22,520: INFO: common: created directory at: artifacts/data_ingestion]
[2024-06-22 21:05:22,526: INFO: data_ingestion: File already exists of size: ~ 74490 KB]
[2024-06-22 21:05:22,528: INFO: data_ingestion:  File 'artifacts/data_ingestion/card_transdata.csv' is of type '.csv']
[2024-06-22 21:05:22,528: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-06-22 21:05:22,530: INFO: main: *******************]
[2024-06-22 21:05:22,532: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-06-22 21:05:22,537: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 21:05:22,541: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 21:05:22,548: INFO: common: created directory at: artifacts]
[2024-06-22 21:05:22,554: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-06-22 21:05:22,555: INFO: prepare_base_model: Initialized XGBClassifier with following parameters PrepareBaseModelConfig(params_n_estimators=500, params_learning_rate=0.1, params_random_state=42, params_subsample=0.5, params_n_jobs=-1, params_max_depth=3)]
[2024-06-22 21:05:22,556: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-06-22 21:05:22,558: INFO: main: *******************]
[2024-06-22 21:05:22,561: INFO: main: >>>>>> stage Train and save model started <<<<<<]
[2024-06-22 21:05:22,566: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 21:05:22,569: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 21:05:22,570: INFO: common: created directory at: artifacts]
[2024-06-22 21:05:22,573: INFO: common: created directory at: artifacts/training]
[2024-06-22 21:05:24,152: INFO: training: Model training and cross validation initiated.]
[2024-06-22 21:07:13,386: INFO: training: Cross Validation Scores: [0.99063215 0.98941648 0.9902746  0.98820164 0.98905971]]
[2024-06-22 21:07:13,387: INFO: training: Scores Mean:  0.9895169155985206]
[2024-06-22 21:07:13,388: INFO: training: Scores Standard Deviation: 0.0008679747406873597]
[2024-06-22 21:07:37,221: INFO: training: Model saved in path artifacts/training/model.pkl.]
[2024-06-22 21:07:37,221: INFO: main: >>>>>> stage Train and save model completed <<<<<<

x==========x]
[2024-06-22 21:07:37,223: INFO: main: *******************]
[2024-06-22 21:07:37,224: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-06-22 21:07:37,230: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 21:07:37,235: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 21:07:37,236: INFO: common: created directory at: artifacts]
[2024-06-22 21:07:37,237: ERROR: main: name 'params' is not defined]
Traceback (most recent call last):
  File "/home/nair.ro/mlops-model-dev/main.py", line 52, in <module>
    model_evalution.main(xgb)
  File "/home/nair.ro/mlops-model-dev/src/XGBClassifier/pipeline/stage_04_evaluation.py", line 17, in main
    val_config = config.get_validation_config()
  File "/home/nair.ro/mlops-model-dev/src/XGBClassifier/config_mngr/configuration_manager.py", line 84, in get_validation_config
    all_params=params,
NameError: name 'params' is not defined
[2024-06-22 21:08:52,505: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-06-22 21:08:52,509: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 21:08:52,512: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 21:08:52,513: INFO: common: created directory at: artifacts]
[2024-06-22 21:08:52,514: INFO: common: created directory at: artifacts/data_ingestion]
[2024-06-22 21:08:52,516: INFO: data_ingestion: File already exists of size: ~ 74490 KB]
[2024-06-22 21:08:52,518: INFO: data_ingestion:  File 'artifacts/data_ingestion/card_transdata.csv' is of type '.csv']
[2024-06-22 21:08:52,518: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-06-22 21:08:52,520: INFO: main: *******************]
[2024-06-22 21:08:52,521: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-06-22 21:08:52,525: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 21:08:52,527: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 21:08:52,528: INFO: common: created directory at: artifacts]
[2024-06-22 21:08:52,530: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-06-22 21:08:52,532: INFO: prepare_base_model: Initialized XGBClassifier with following parameters PrepareBaseModelConfig(params_n_estimators=500, params_learning_rate=0.1, params_random_state=42, params_subsample=0.5, params_n_jobs=-1, params_max_depth=3)]
[2024-06-22 21:08:52,533: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-06-22 21:08:52,534: INFO: main: *******************]
[2024-06-22 21:08:52,535: INFO: main: >>>>>> stage Train and save model started <<<<<<]
[2024-06-22 21:08:52,539: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 21:08:52,541: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 21:08:52,542: INFO: common: created directory at: artifacts]
[2024-06-22 21:08:52,543: INFO: common: created directory at: artifacts/training]
[2024-06-22 21:08:53,854: INFO: training: Model training and cross validation initiated.]
[2024-06-22 21:10:39,591: INFO: training: Cross Validation Scores: [0.99063215 0.98941648 0.9902746  0.98820164 0.98905971]]
[2024-06-22 21:10:39,592: INFO: training: Scores Mean:  0.9895169155985206]
[2024-06-22 21:10:39,594: INFO: training: Scores Standard Deviation: 0.0008679747406873597]
[2024-06-22 21:11:03,371: INFO: training: Model saved in path artifacts/training/model.pkl.]
[2024-06-22 21:11:03,372: INFO: main: >>>>>> stage Train and save model completed <<<<<<

x==========x]
[2024-06-22 21:11:03,374: INFO: main: *******************]
[2024-06-22 21:11:03,379: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-06-22 21:11:03,387: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 21:11:03,390: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 21:11:03,392: INFO: common: created directory at: artifacts]
[2024-06-22 21:11:10,933: INFO: common: Figure saved as: confusion_matrix_20240622_211109.png]
[2024-06-22 21:11:15,035: ERROR: main: name 'precision_recall_curve' is not defined]
Traceback (most recent call last):
  File "/home/nair.ro/mlops-model-dev/main.py", line 52, in <module>
    model_evalution.main(xgb)
  File "/home/nair.ro/mlops-model-dev/src/XGBClassifier/pipeline/stage_04_evaluation.py", line 21, in main
    evalu.precision_recall_trade_off(xgb)
  File "/home/nair.ro/mlops-model-dev/src/XGBClassifier/components/evaluation.py", line 35, in precision_recall_trade_off
    precision ,recall ,threshold = precision_recall_curve(y_test,y_proba[:,1])
NameError: name 'precision_recall_curve' is not defined
[2024-06-22 21:12:39,176: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-06-22 21:12:39,180: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 21:12:39,183: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 21:12:39,184: INFO: common: created directory at: artifacts]
[2024-06-22 21:12:39,187: INFO: common: created directory at: artifacts/data_ingestion]
[2024-06-22 21:12:39,189: INFO: data_ingestion: File already exists of size: ~ 74490 KB]
[2024-06-22 21:12:39,191: INFO: data_ingestion:  File 'artifacts/data_ingestion/card_transdata.csv' is of type '.csv']
[2024-06-22 21:12:39,191: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-06-22 21:12:39,192: INFO: main: *******************]
[2024-06-22 21:12:39,195: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-06-22 21:12:39,197: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 21:12:39,200: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 21:12:39,201: INFO: common: created directory at: artifacts]
[2024-06-22 21:12:39,202: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-06-22 21:12:39,203: INFO: prepare_base_model: Initialized XGBClassifier with following parameters PrepareBaseModelConfig(params_n_estimators=500, params_learning_rate=0.1, params_random_state=42, params_subsample=0.5, params_n_jobs=-1, params_max_depth=3)]
[2024-06-22 21:12:39,204: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-06-22 21:12:39,205: INFO: main: *******************]
[2024-06-22 21:12:39,206: INFO: main: >>>>>> stage Train and save model started <<<<<<]
[2024-06-22 21:12:39,209: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 21:12:39,212: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 21:12:39,214: INFO: common: created directory at: artifacts]
[2024-06-22 21:12:39,215: INFO: common: created directory at: artifacts/training]
[2024-06-22 21:12:40,504: INFO: training: Model training and cross validation initiated.]
[2024-06-22 21:14:30,633: INFO: training: Cross Validation Scores: [0.99063215 0.98941648 0.9902746  0.98820164 0.98905971]]
[2024-06-22 21:14:30,635: INFO: training: Scores Mean:  0.9895169155985206]
[2024-06-22 21:14:30,638: INFO: training: Scores Standard Deviation: 0.0008679747406873597]
[2024-06-22 21:14:54,670: INFO: training: Model saved in path artifacts/training/model.pkl.]
[2024-06-22 21:14:54,671: INFO: main: >>>>>> stage Train and save model completed <<<<<<

x==========x]
[2024-06-22 21:14:54,672: INFO: main: *******************]
[2024-06-22 21:14:54,674: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-06-22 21:14:54,679: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 21:14:54,681: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 21:14:54,684: INFO: common: created directory at: artifacts]
[2024-06-22 21:15:01,838: INFO: common: Figure saved as: confusion_matrix_20240622_211500.png]
[2024-06-22 21:15:18,283: INFO: common: Figure saved as: precision_recall_curve_20240622_211507.png]
[2024-06-22 21:15:18,290: INFO: evaluation:         Threshold  Precision  Recall
179722   0.001308   0.967030     1.0
179723   0.001317   0.967083     1.0
179724   0.001319   0.967137     1.0
179725   0.001330   0.967190     1.0
179726   0.001333   0.967244     1.0
179727   0.001334   0.967297     1.0
179728   0.001337   0.967351     1.0
179729   0.001337   0.967405     1.0
179730   0.001338   0.967458     1.0
179731   0.001340   0.967512     1.0]
[2024-06-22 21:15:18,317: ERROR: main: name 'save_json' is not defined]
Traceback (most recent call last):
  File "/home/nair.ro/mlops-model-dev/main.py", line 52, in <module>
    model_evalution.main(xgb)
  File "/home/nair.ro/mlops-model-dev/src/XGBClassifier/pipeline/stage_04_evaluation.py", line 21, in main
    evalu.precision_recall_trade_off(xgb)
  File "/home/nair.ro/mlops-model-dev/src/XGBClassifier/components/evaluation.py", line 49, in precision_recall_trade_off
    save_json(path=Path("prt.json"), data=prt)
NameError: name 'save_json' is not defined
[2024-06-22 21:15:54,581: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-06-22 21:15:54,585: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 21:15:54,590: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 21:15:54,590: INFO: common: created directory at: artifacts]
[2024-06-22 21:15:54,592: INFO: common: created directory at: artifacts/data_ingestion]
[2024-06-22 21:15:54,593: INFO: data_ingestion: File already exists of size: ~ 74490 KB]
[2024-06-22 21:15:54,595: INFO: data_ingestion:  File 'artifacts/data_ingestion/card_transdata.csv' is of type '.csv']
[2024-06-22 21:15:54,595: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-06-22 21:15:54,597: INFO: main: *******************]
[2024-06-22 21:15:54,597: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-06-22 21:15:54,602: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 21:15:54,605: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 21:15:54,605: INFO: common: created directory at: artifacts]
[2024-06-22 21:15:54,607: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-06-22 21:15:54,608: INFO: prepare_base_model: Initialized XGBClassifier with following parameters PrepareBaseModelConfig(params_n_estimators=500, params_learning_rate=0.1, params_random_state=42, params_subsample=0.5, params_n_jobs=-1, params_max_depth=3)]
[2024-06-22 21:15:54,609: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-06-22 21:15:54,610: INFO: main: *******************]
[2024-06-22 21:15:54,611: INFO: main: >>>>>> stage Train and save model started <<<<<<]
[2024-06-22 21:15:54,616: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 21:15:54,619: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 21:15:54,620: INFO: common: created directory at: artifacts]
[2024-06-22 21:15:54,621: INFO: common: created directory at: artifacts/training]
[2024-06-22 21:15:55,976: INFO: training: Model training and cross validation initiated.]
[2024-06-22 21:17:40,518: INFO: training: Cross Validation Scores: [0.99063215 0.98941648 0.9902746  0.98820164 0.98905971]]
[2024-06-22 21:17:40,520: INFO: training: Scores Mean:  0.9895169155985206]
[2024-06-22 21:17:40,520: INFO: training: Scores Standard Deviation: 0.0008679747406873597]
[2024-06-22 21:18:05,168: INFO: training: Model saved in path artifacts/training/model.pkl.]
[2024-06-22 21:18:05,170: INFO: main: >>>>>> stage Train and save model completed <<<<<<

x==========x]
[2024-06-22 21:18:05,183: INFO: main: *******************]
[2024-06-22 21:18:05,190: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-06-22 21:18:05,199: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 21:18:05,204: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 21:18:05,205: INFO: common: created directory at: artifacts]
[2024-06-22 21:18:11,749: INFO: common: Figure saved as: confusion_matrix_20240622_211810.png]
[2024-06-22 21:18:26,482: INFO: common: Figure saved as: precision_recall_curve_20240622_211815.png]
[2024-06-22 21:18:26,490: INFO: evaluation:         Threshold  Precision  Recall
179722   0.001308   0.967030     1.0
179723   0.001317   0.967083     1.0
179724   0.001319   0.967137     1.0
179725   0.001330   0.967190     1.0
179726   0.001333   0.967244     1.0
179727   0.001334   0.967297     1.0
179728   0.001337   0.967351     1.0
179729   0.001337   0.967405     1.0
179730   0.001338   0.967458     1.0
179731   0.001340   0.967512     1.0]
[2024-06-22 21:18:26,505: ERROR: main: Argument data of type <class 'pandas.core.frame.DataFrame'> to <function save_json at 0x2b29129555a0> does not match annotation type <class 'dict'>]
Traceback (most recent call last):
  File "/home/nair.ro/mlops-model-dev/main.py", line 52, in <module>
    model_evalution.main(xgb)
  File "/home/nair.ro/mlops-model-dev/src/XGBClassifier/pipeline/stage_04_evaluation.py", line 21, in main
    evalu.precision_recall_trade_off(xgb)
  File "/home/nair.ro/mlops-model-dev/src/XGBClassifier/components/evaluation.py", line 49, in precision_recall_trade_off
    save_json(path=Path("prt.json"), data=prt)
  File "/home/nair.ro/miniforge3/lib/python3.10/site-packages/ensure/main.py", line 803, in __call__
    raise EnsureError(msg.format(
ensure.main.EnsureError: Argument data of type <class 'pandas.core.frame.DataFrame'> to <function save_json at 0x2b29129555a0> does not match annotation type <class 'dict'>
[2024-06-22 21:20:42,021: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-06-22 21:20:42,025: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 21:20:42,027: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 21:20:42,029: INFO: common: created directory at: artifacts]
[2024-06-22 21:20:42,033: INFO: common: created directory at: artifacts/data_ingestion]
[2024-06-22 21:20:42,037: INFO: data_ingestion: File already exists of size: ~ 74490 KB]
[2024-06-22 21:20:42,039: INFO: data_ingestion:  File 'artifacts/data_ingestion/card_transdata.csv' is of type '.csv']
[2024-06-22 21:20:42,040: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-06-22 21:20:42,040: INFO: main: *******************]
[2024-06-22 21:20:42,040: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-06-22 21:20:42,043: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 21:20:42,048: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 21:20:42,049: INFO: common: created directory at: artifacts]
[2024-06-22 21:20:42,049: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-06-22 21:20:42,050: INFO: prepare_base_model: Initialized XGBClassifier with following parameters PrepareBaseModelConfig(params_n_estimators=500, params_learning_rate=0.1, params_random_state=42, params_subsample=0.5, params_n_jobs=-1, params_max_depth=3)]
[2024-06-22 21:20:42,050: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-06-22 21:20:42,050: INFO: main: *******************]
[2024-06-22 21:20:42,050: INFO: main: >>>>>> stage Train and save model started <<<<<<]
[2024-06-22 21:20:42,053: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 21:20:42,057: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 21:20:42,059: INFO: common: created directory at: artifacts]
[2024-06-22 21:20:42,060: INFO: common: created directory at: artifacts/training]
[2024-06-22 21:20:43,896: INFO: training: Model training and cross validation initiated.]
[2024-06-22 21:23:01,115: INFO: training: Cross Validation Scores: [0.99063215 0.98941648 0.9902746  0.98820164 0.98905971]]
[2024-06-22 21:23:01,116: INFO: training: Scores Mean:  0.9895169155985206]
[2024-06-22 21:23:01,117: INFO: training: Scores Standard Deviation: 0.0008679747406873597]
[2024-06-22 21:23:25,080: INFO: training: Model saved in path artifacts/training/model.pkl.]
[2024-06-22 21:23:25,081: INFO: main: >>>>>> stage Train and save model completed <<<<<<

x==========x]
[2024-06-22 21:23:25,081: INFO: main: *******************]
[2024-06-22 21:23:25,081: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-06-22 21:23:25,084: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 21:23:25,087: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 21:23:25,089: INFO: common: created directory at: artifacts]
[2024-06-22 21:23:31,817: INFO: common: Figure saved as: confusion_matrix_20240622_212330.png]
[2024-06-22 21:23:46,587: INFO: common: Figure saved as: precision_recall_curve_20240622_212335.png]
[2024-06-22 21:23:46,595: INFO: evaluation:         Threshold  Precision  Recall
179722   0.001308   0.967030     1.0
179723   0.001317   0.967083     1.0
179724   0.001319   0.967137     1.0
179725   0.001330   0.967190     1.0
179726   0.001333   0.967244     1.0
179727   0.001334   0.967297     1.0
179728   0.001337   0.967351     1.0
179729   0.001337   0.967405     1.0
179730   0.001338   0.967458     1.0
179731   0.001340   0.967512     1.0]
[2024-06-22 21:23:46,616: ERROR: main: Argument data of type <class 'list'> to <function save_json at 0x2b7d4e74d5a0> does not match annotation type <class 'dict'>]
Traceback (most recent call last):
  File "/home/nair.ro/mlops-model-dev/main.py", line 52, in <module>
    model_evalution.main(xgb)
  File "/home/nair.ro/mlops-model-dev/src/XGBClassifier/pipeline/stage_04_evaluation.py", line 21, in main
    evalu.precision_recall_trade_off(xgb)
  File "/home/nair.ro/mlops-model-dev/src/XGBClassifier/components/evaluation.py", line 51, in precision_recall_trade_off
    save_json(path=Path("prt.json"), data=prt_dict)
  File "/home/nair.ro/miniforge3/lib/python3.10/site-packages/ensure/main.py", line 803, in __call__
    raise EnsureError(msg.format(
ensure.main.EnsureError: Argument data of type <class 'list'> to <function save_json at 0x2b7d4e74d5a0> does not match annotation type <class 'dict'>
[2024-06-22 21:26:14,937: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-06-22 21:26:14,943: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 21:26:14,949: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 21:26:14,952: INFO: common: created directory at: artifacts]
[2024-06-22 21:26:14,953: INFO: common: created directory at: artifacts/data_ingestion]
[2024-06-22 21:26:14,956: INFO: data_ingestion: File already exists of size: ~ 74490 KB]
[2024-06-22 21:26:14,961: INFO: data_ingestion:  File 'artifacts/data_ingestion/card_transdata.csv' is of type '.csv']
[2024-06-22 21:26:14,964: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-06-22 21:26:14,964: INFO: main: *******************]
[2024-06-22 21:26:14,965: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-06-22 21:26:14,968: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 21:26:14,971: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 21:26:14,973: INFO: common: created directory at: artifacts]
[2024-06-22 21:26:14,975: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-06-22 21:26:14,976: INFO: prepare_base_model: Initialized XGBClassifier with following parameters PrepareBaseModelConfig(params_n_estimators=500, params_learning_rate=0.1, params_random_state=42, params_subsample=0.5, params_n_jobs=-1, params_max_depth=3)]
[2024-06-22 21:26:14,976: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-06-22 21:26:14,976: INFO: main: *******************]
[2024-06-22 21:26:14,976: INFO: main: >>>>>> stage Train and save model started <<<<<<]
[2024-06-22 21:26:14,981: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 21:26:14,983: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 21:26:14,984: INFO: common: created directory at: artifacts]
[2024-06-22 21:26:14,986: INFO: common: created directory at: artifacts/training]
[2024-06-22 21:26:16,403: INFO: training: Model training and cross validation initiated.]
[2024-06-22 21:28:01,672: INFO: training: Cross Validation Scores: [0.99063215 0.98941648 0.9902746  0.98820164 0.98905971]]
[2024-06-22 21:28:01,675: INFO: training: Scores Mean:  0.9895169155985206]
[2024-06-22 21:28:01,675: INFO: training: Scores Standard Deviation: 0.0008679747406873597]
[2024-06-22 21:28:27,546: INFO: training: Model saved in path artifacts/training/model.pkl.]
[2024-06-22 21:28:27,547: INFO: main: >>>>>> stage Train and save model completed <<<<<<

x==========x]
[2024-06-22 21:28:27,548: INFO: main: *******************]
[2024-06-22 21:28:27,548: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-06-22 21:28:27,553: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 21:28:27,556: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 21:28:27,560: INFO: common: created directory at: artifacts]
[2024-06-22 21:28:36,511: INFO: common: Figure saved as: confusion_matrix_20240622_212835.png]
[2024-06-22 21:28:51,433: INFO: common: Figure saved as: precision_recall_curve_20240622_212840.png]
[2024-06-22 21:28:51,443: INFO: evaluation:         Threshold  Precision  Recall
179722   0.001308   0.967030     1.0
179723   0.001317   0.967083     1.0
179724   0.001319   0.967137     1.0
179725   0.001330   0.967190     1.0
179726   0.001333   0.967244     1.0
179727   0.001334   0.967297     1.0
179728   0.001337   0.967351     1.0
179729   0.001337   0.967405     1.0
179730   0.001338   0.967458     1.0
179731   0.001340   0.967512     1.0]
[2024-06-22 21:28:51,493: INFO: common: json file saved at: prt.json]
[2024-06-22 21:29:06,042: INFO: common: Figure saved as: precision_recall_curve_20240622_212855.png]
[2024-06-22 21:29:06,049: INFO: evaluation:         Threshold  Precision  Recall
179722   0.001308   0.967030     1.0
179723   0.001317   0.967083     1.0
179724   0.001319   0.967137     1.0
179725   0.001330   0.967190     1.0
179726   0.001333   0.967244     1.0
179727   0.001334   0.967297     1.0
179728   0.001337   0.967351     1.0
179729   0.001337   0.967405     1.0
179730   0.001338   0.967458     1.0
179731   0.001340   0.967512     1.0]
[2024-06-22 21:29:06,087: INFO: common: json file saved at: prt.json]
[2024-06-22 21:29:06,092: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
