[2024-06-22 15:00:31,335: INFO: main: Starting Custom logging...]
[2024-06-22 15:43:38,234: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 15:43:38,237: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 15:51:03,414: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 15:51:03,418: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 15:51:03,423: INFO: common: created directory at: artifacts]
[2024-06-22 15:51:03,433: INFO: common: created directory at: artifacts/data_ingestion]
[2024-06-22 15:51:07,250: INFO: 2391244112:  file from url https://drive.google.com/uc?/export=download&id=1RmDs2j3QcY05ixoV1-ACmxmnM5xdmiGF downloaded and saved at path artifacts/data_ingestion/card_transdata.zip]
[2024-06-22 15:51:43,659: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 15:51:43,664: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 15:51:43,668: INFO: common: created directory at: artifacts]
[2024-06-22 15:51:43,671: INFO: common: created directory at: artifacts/data_ingestion]
[2024-06-22 15:51:43,676: INFO: 2391244112: File already exists of size: ~ 74490 KB]
[2024-06-22 15:51:50,647: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 15:51:50,652: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 15:51:50,655: INFO: common: created directory at: artifacts]
[2024-06-22 15:51:50,659: INFO: common: created directory at: artifacts/data_ingestion]
[2024-06-22 15:51:50,663: INFO: 2391244112: File already exists of size: ~ 74490 KB]
[2024-06-22 15:52:10,582: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 15:52:10,587: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 15:52:10,596: INFO: common: created directory at: artifacts]
[2024-06-22 15:52:10,609: INFO: common: created directory at: artifacts/data_ingestion]
[2024-06-22 15:52:14,945: INFO: 2391244112:  file from url https://drive.google.com/uc?/export=download&id=1RmDs2j3QcY05ixoV1-ACmxmnM5xdmiGF downloaded and saved at path artifacts/data_ingestion/card_transdata.zip]
[2024-06-22 15:54:15,295: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 15:54:15,302: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 15:54:15,318: INFO: common: created directory at: artifacts]
[2024-06-22 15:54:15,325: INFO: common: created directory at: artifacts/data_ingestion]
[2024-06-22 15:54:15,336: INFO: 2494678114: File already exists of size: ~ 74490 KB]
[2024-06-22 15:54:25,557: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 15:54:25,564: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 15:54:25,580: INFO: common: created directory at: artifacts]
[2024-06-22 15:54:25,606: INFO: common: created directory at: artifacts/data_ingestion]
[2024-06-22 15:54:30,180: INFO: 2494678114:  file from url https://drive.google.com/uc?/export=download&id=1RmDs2j3QcY05ixoV1-ACmxmnM5xdmiGF downloaded and saved at path artifacts/data_ingestion/card_transdata.zip]
[2024-06-22 15:54:47,959: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 15:54:47,963: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 15:54:47,966: INFO: common: created directory at: artifacts]
[2024-06-22 15:54:47,971: INFO: common: created directory at: artifacts/data_ingestion]
[2024-06-22 15:54:47,974: INFO: 2494678114: File already exists of size: ~ 74490 KB]
[2024-06-22 15:55:32,663: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 15:55:32,669: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 15:55:32,681: INFO: common: created directory at: artifacts]
[2024-06-22 15:55:32,689: INFO: common: created directory at: artifacts/data_ingestion]
[2024-06-22 15:55:32,694: INFO: 2494678114: File already exists of size: ~ 4 KB]
[2024-06-22 15:56:25,554: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 15:56:25,558: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 15:56:25,561: INFO: common: created directory at: artifacts]
[2024-06-22 15:56:25,563: INFO: common: created directory at: artifacts/data_ingestion]
[2024-06-22 15:56:28,634: INFO: 2494678114:  file from url https://drive.google.com/uc?/export=download&id=1RmDs2j3QcY05ixoV1-ACmxmnM5xdmiGF downloaded and saved at path artifacts/data_ingestion/card_transdata.csv]
[2024-06-22 16:13:57,884: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-06-22 16:13:57,886: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 16:13:57,888: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 16:13:57,889: INFO: common: created directory at: artifacts]
[2024-06-22 16:13:57,890: INFO: common: created directory at: artifacts/data_ingestion]
[2024-06-22 16:13:57,892: ERROR: stage_01_data_ingestion: name 'url' is not defined]
Traceback (most recent call last):
  File "/home/nair.ro/mlops-model-dev/src/XGBClassifier/pipeline/stage_01_data_ingestion.py", line 25, in <module>
    obj.main()
  File "/home/nair.ro/mlops-model-dev/src/XGBClassifier/pipeline/stage_01_data_ingestion.py", line 16, in main
    data_ingestion.download_file()
  File "/home/nair.ro/mlops-model-dev/src/XGBClassifier/components/data_ingestion.py", line 19, in download_file
    file_id = url.split("/")[-2]
NameError: name 'url' is not defined
[2024-06-22 16:15:35,743: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-06-22 16:15:35,745: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 16:15:35,747: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 16:15:35,748: INFO: common: created directory at: artifacts]
[2024-06-22 16:15:35,749: INFO: common: created directory at: artifacts/data_ingestion]
[2024-06-22 16:15:35,750: ERROR: stage_01_data_ingestion: name 'gdown' is not defined]
Traceback (most recent call last):
  File "/home/nair.ro/mlops-model-dev/src/XGBClassifier/pipeline/stage_01_data_ingestion.py", line 25, in <module>
    obj.main()
  File "/home/nair.ro/mlops-model-dev/src/XGBClassifier/pipeline/stage_01_data_ingestion.py", line 16, in main
    data_ingestion.download_file()
  File "/home/nair.ro/mlops-model-dev/src/XGBClassifier/components/data_ingestion.py", line 21, in download_file
    gdown.download(prefix+file_id, self.config.local_data_file)
NameError: name 'gdown' is not defined
[2024-06-22 16:15:47,108: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-06-22 16:15:47,111: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 16:15:47,113: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 16:15:47,114: INFO: common: created directory at: artifacts]
[2024-06-22 16:15:47,115: INFO: common: created directory at: artifacts/data_ingestion]
[2024-06-22 16:15:47,117: ERROR: stage_01_data_ingestion: name 'gdown' is not defined]
Traceback (most recent call last):
  File "/home/nair.ro/mlops-model-dev/src/XGBClassifier/pipeline/stage_01_data_ingestion.py", line 25, in <module>
    obj.main()
  File "/home/nair.ro/mlops-model-dev/src/XGBClassifier/pipeline/stage_01_data_ingestion.py", line 16, in main
    data_ingestion.download_file()
  File "/home/nair.ro/mlops-model-dev/src/XGBClassifier/components/data_ingestion.py", line 21, in download_file
    gdown.download(prefix+file_id, self.config.local_data_file)
NameError: name 'gdown' is not defined
[2024-06-22 16:16:00,694: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-06-22 16:16:00,697: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 16:16:00,698: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 16:16:00,699: INFO: common: created directory at: artifacts]
[2024-06-22 16:16:00,700: INFO: common: created directory at: artifacts/data_ingestion]
[2024-06-22 16:16:04,819: INFO: data_ingestion:  file from url https://drive.google.com/uc?/export=download&id=1RmDs2j3QcY05ixoV1-ACmxmnM5xdmiGF downloaded and saved at path artifacts/data_ingestion/card_transdata.csv]
[2024-06-22 16:16:04,834: INFO: data_ingestion:  File 'artifacts/data_ingestion/card_transdata.csv' is of type '.csv']
[2024-06-22 16:16:04,835: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-06-22 16:19:45,704: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-06-22 16:19:45,707: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 16:19:45,711: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 16:19:45,713: INFO: common: created directory at: artifacts]
[2024-06-22 16:19:45,714: INFO: common: created directory at: artifacts/data_ingestion]
[2024-06-22 16:19:50,031: INFO: data_ingestion:  file from url https://drive.google.com/uc?/export=download&id=1RmDs2j3QcY05ixoV1-ACmxmnM5xdmiGF downloaded and saved at path artifacts/data_ingestion/card_transdata.csv]
[2024-06-22 16:19:50,047: INFO: data_ingestion:  File 'artifacts/data_ingestion/card_transdata.csv' is of type '.csv']
[2024-06-22 16:19:50,048: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-06-22 16:22:39,245: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-06-22 16:22:39,249: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 16:22:39,252: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 16:22:39,255: INFO: common: created directory at: artifacts]
[2024-06-22 16:22:39,256: INFO: common: created directory at: artifacts/data_ingestion]
[2024-06-22 16:22:42,463: INFO: data_ingestion:  file from url https://drive.google.com/uc?/export=download&id=1RmDs2j3QcY05ixoV1-ACmxmnM5xdmiGF downloaded and saved at path artifacts/data_ingestion/card_transdata.csv]
[2024-06-22 16:22:42,485: INFO: data_ingestion:  File 'artifacts/data_ingestion/card_transdata.csv' is of type '.csv']
[2024-06-22 16:22:42,486: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-06-22 17:05:08,713: INFO: stage_02_prepare_base_model: *******************]
[2024-06-22 17:05:08,713: INFO: stage_02_prepare_base_model: >>>>>> stage Prepare base model started <<<<<<]
[2024-06-22 17:05:08,717: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 17:05:08,720: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 17:05:08,721: INFO: common: created directory at: artifacts]
[2024-06-22 17:05:08,725: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-06-22 17:05:08,725: ERROR: stage_02_prepare_base_model: "'ConfigBox' object has no attribute 'base_model_path'"]
Traceback (most recent call last):
  File "box/box.py", line 503, in box.box.Box.__getitem__
KeyError: 'base_model_path'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "box/box.py", line 536, in box.box.Box.__getattr__
  File "box/box.py", line 524, in box.box.Box.__getitem__
box.exceptions.BoxKeyError: "'base_model_path'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "box/box.py", line 538, in box.box.Box.__getattr__
AttributeError: 'ConfigBox' object has no attribute 'base_model_path'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "box/config_box.py", line 28, in box.config_box.ConfigBox.__getattr__
  File "box/box.py", line 552, in box.box.Box.__getattr__
box.exceptions.BoxKeyError: "'ConfigBox' object has no attribute 'base_model_path'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "box/box.py", line 503, in box.box.Box.__getitem__
KeyError: 'base_model_path'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "box/box.py", line 536, in box.box.Box.__getattr__
  File "box/box.py", line 524, in box.box.Box.__getitem__
box.exceptions.BoxKeyError: "'base_model_path'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "box/box.py", line 538, in box.box.Box.__getattr__
AttributeError: 'ConfigBox' object has no attribute 'base_model_path'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/nair.ro/mlops-model-dev/src/XGBClassifier/pipeline/stage_02_prepare_base_model.py", line 25, in <module>
    obj.main()
  File "/home/nair.ro/mlops-model-dev/src/XGBClassifier/pipeline/stage_02_prepare_base_model.py", line 14, in main
    prepare_base_model_config = config.get_prepare_base_model_config()
  File "/home/nair.ro/ChickenDiseasaeClassification/src/cnnClassifier/config/configuration.py", line 50, in get_prepare_base_model_config
    base_model_path=Path(config.base_model_path),
  File "box/config_box.py", line 30, in box.config_box.ConfigBox.__getattr__
  File "box/box.py", line 552, in box.box.Box.__getattr__
box.exceptions.BoxKeyError: "'ConfigBox' object has no attribute 'base_model_path'"
[2024-06-22 17:09:55,499: INFO: stage_02_prepare_base_model: *******************]
[2024-06-22 17:09:55,499: INFO: stage_02_prepare_base_model: >>>>>> stage Prepare base model started <<<<<<]
[2024-06-22 17:09:55,502: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 17:09:55,506: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 17:09:55,507: INFO: common: created directory at: artifacts]
[2024-06-22 17:09:55,508: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-06-22 17:09:55,508: ERROR: stage_02_prepare_base_model: name 'XGBClassifier' is not defined]
Traceback (most recent call last):
  File "/home/nair.ro/mlops-model-dev/src/XGBClassifier/pipeline/stage_02_prepare_base_model.py", line 26, in <module>
    obj.main()
  File "/home/nair.ro/mlops-model-dev/src/XGBClassifier/pipeline/stage_02_prepare_base_model.py", line 17, in main
    xgb = prepare_base_model.prepare_XGBClassifier_model()
  File "/home/nair.ro/mlops-model-dev/src/XGBClassifier/components/prepare_base_model.py", line 12, in prepare_XGBClassifier_model
    xgb = XGBClassifier(n_estimators=self.config.params_n_estimators ,
NameError: name 'XGBClassifier' is not defined
[2024-06-22 17:10:44,752: INFO: stage_02_prepare_base_model: *******************]
[2024-06-22 17:10:44,753: INFO: stage_02_prepare_base_model: >>>>>> stage Prepare base model started <<<<<<]
[2024-06-22 17:10:44,755: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 17:10:44,757: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 17:10:44,758: INFO: common: created directory at: artifacts]
[2024-06-22 17:10:44,759: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-06-22 17:10:44,760: ERROR: stage_02_prepare_base_model: name 'logger' is not defined]
Traceback (most recent call last):
  File "/home/nair.ro/mlops-model-dev/src/XGBClassifier/pipeline/stage_02_prepare_base_model.py", line 26, in <module>
    obj.main()
  File "/home/nair.ro/mlops-model-dev/src/XGBClassifier/pipeline/stage_02_prepare_base_model.py", line 17, in main
    xgb = prepare_base_model.prepare_XGBClassifier_model()
  File "/home/nair.ro/mlops-model-dev/src/XGBClassifier/components/prepare_base_model.py", line 16, in prepare_XGBClassifier_model
    logger.info(f"Initialized XGBClassifier with following parameters {self.config}")
NameError: name 'logger' is not defined
[2024-06-22 17:11:02,418: INFO: stage_02_prepare_base_model: *******************]
[2024-06-22 17:11:02,419: INFO: stage_02_prepare_base_model: >>>>>> stage Prepare base model started <<<<<<]
[2024-06-22 17:11:02,421: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 17:11:02,423: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 17:11:02,424: INFO: common: created directory at: artifacts]
[2024-06-22 17:11:02,425: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-06-22 17:11:02,426: INFO: prepare_base_model: Initialized XGBClassifier with following parameters PrepareBaseModelConfig(params_n_estimators=500, params_learning_rate=0.1, params_random_state=42, params_subsample=0.5, params_n_jobs=-1, params_max_depth=3)]
[2024-06-22 17:11:02,426: INFO: stage_02_prepare_base_model: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-06-22 17:12:39,495: INFO: stage_02_prepare_base_model: *******************]
[2024-06-22 17:12:39,495: INFO: stage_02_prepare_base_model: >>>>>> stage Prepare base model started <<<<<<]
[2024-06-22 17:12:39,498: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-06-22 17:12:39,500: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-22 17:12:39,500: INFO: common: created directory at: artifacts]
[2024-06-22 17:12:39,501: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-06-22 17:12:39,502: INFO: prepare_base_model: Initialized XGBClassifier with following parameters PrepareBaseModelConfig(params_n_estimators=500, params_learning_rate=0.1, params_random_state=42, params_subsample=0.5, params_n_jobs=-1, params_max_depth=3)]
[2024-06-22 17:12:39,503: INFO: stage_02_prepare_base_model: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
